/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.admin.quanlyquidinh;

import bus.NhanvienBUS;
import bus.QuydinhBUS;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;
import pojos.Nhanvien;
import pojos.Quydinh;
import pojos.Taikhoan;
import util.ui.CustomCenterAlignmentRenderer;
import util.ui.CustomDateRenderer;
import util.ui.CustomLeftAlignmentRenderer;

/**
 *
 * @author HAO
 */
public class QuanLyQuyDinhPane extends javax.swing.JPanel {

    private DefaultTableModel dtm;
    private List<Quydinh> listQuydinhs;
    public static final Color SELCECTED_COLOR = new Color(208, 218, 253);
    public static final Color EVEN_COLOR = new Color(255, 255, 255);
    public static final Color ODD_COLOR = new Color(230, 230, 230);

    /**
     * Creates new form QuanLyQuyDinhPane
     */
    public QuanLyQuyDinhPane() {
        initComponents();

        setupTable();
        fillUpData();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jLabel1 = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tableScrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable(){
            @Override
            public Component prepareRenderer(TableCellRenderer renderer, int row, int column) {
                Component c = super.prepareRenderer(renderer, row, column);
                if (isRowSelected(row)) {
                    c.setBackground(SELCECTED_COLOR);
                } else {

                    Color color = row % 2 == 0? EVEN_COLOR : ODD_COLOR;
                    c.setBackground(color);
                }
                return c;
            }
        };
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(250, 250, 250));
        setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(9, 115, 185));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20));
        jPanel4.setMaximumSize(new java.awt.Dimension(32767, 200));
        jPanel4.setPreferredSize(new java.awt.Dimension(120, 80));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));
        jPanel4.add(filler1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bảng quy định");
        jPanel4.add(jLabel1);
        jPanel4.add(filler2);

        add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setPreferredSize(new java.awt.Dimension(150, 427));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_START);

        tableScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        table.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tên quy định", "Đơn vị tính", "Giá trị", "Tình trạng", "Tác vụ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        table.setFillsViewportHeight(true);
        table.setShowVerticalLines(false);
        table.getTableHeader().setReorderingAllowed(false);
        tableScrollPane.setViewportView(table);

        jPanel1.add(tableScrollPane, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(250, 250, 250));
        jPanel3.setPreferredSize(new java.awt.Dimension(150, 427));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel6.setBackground(new java.awt.Color(250, 250, 250));
        jPanel6.setPreferredSize(new java.awt.Dimension(689, 30));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1054, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, java.awt.BorderLayout.NORTH);

        jPanel5.setBackground(new java.awt.Color(250, 250, 250));
        jPanel5.setPreferredSize(new java.awt.Dimension(689, 50));
        jPanel5.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1054, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTable table;
    private javax.swing.JScrollPane tableScrollPane;
    // End of variables declaration//GEN-END:variables

    private void setupTable() {
        setupModelForTable();
        setupUIForTable();
    }

    private void setupModelForTable() {
        dtm = new DefaultTableModel() {
            String[] columnsNames = new String[]{
                "Id", "Tên quy định", "Đơn vị tính", "Giá trị", "Tình trạng", "Tác vụ"
            };
            Class[] types = new Class[]{
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            @Override
            public boolean isCellEditable(int row, int column) {
//                return column == (columnsNames.length - 1);
                return true;
            }

            @Override
            public String getColumnName(int column) {
                return columnsNames[column];
            }

            @Override
            public int getColumnCount() {
                return columnsNames.length;
            }
        };

        table.setModel(dtm);

    }

    private void setupUIForTable() {

        //Column
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                TableColumnModel tableColumnModel = table.getColumnModel();
                tableColumnModel.getColumn(0).setPreferredWidth(100);
                tableColumnModel.getColumn(1).setPreferredWidth(450);
                tableColumnModel.getColumn(2).setPreferredWidth(250);
                tableColumnModel.getColumn(3).setPreferredWidth(100);
                tableColumnModel.getColumn(4).setPreferredWidth(200);
                tableColumnModel.getColumn(5).setPreferredWidth(100);
                tableColumnModel.getColumn(0).setCellRenderer(new CustomLeftAlignmentRenderer());
                for (int i = 1; i <= 4; i++) {
                    tableColumnModel.getColumn(i).setCellRenderer(new CustomCenterAlignmentRenderer());
                }

                QuyDinhPanelCellEditorRenderer quyDinhPanelCellEditorRenderer = new QuyDinhPanelCellEditorRenderer();
                int finalIndex = tableColumnModel.getColumnCount() - 1;
                tableColumnModel.getColumn(finalIndex).setCellRenderer(quyDinhPanelCellEditorRenderer);
                tableColumnModel.getColumn(finalIndex).setCellEditor(quyDinhPanelCellEditorRenderer);

            }
        });
        table.setGridColor(Color.BLACK);
        table.setShowGrid(true);
        table.setShowVerticalLines(false);
        table.setRowHeight(60);

        //Header
        JTableHeader tableHeader = table.getTableHeader();
        tableHeader.setPreferredSize(new Dimension(80, 60));
        tableHeader.setFont(new Font("Tahoma", 1, 16));
        tableHeader.setForeground(new Color(34, 103, 190));
        tableHeader.setBackground(new Color(210, 227, 240));
        tableHeader.setReorderingAllowed(false);
        tableHeader.setBorder(BorderFactory.createLineBorder(new Color(102, 102, 102), 1));

    }


    private void fillUpData() {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                listQuydinhs = QuydinhBUS.getListQuyDinh();

                for (Quydinh quydinh : listQuydinhs) {

                    dtm.addRow(new Object[]{
                        quydinh.getIdQuyDinh(),
                        quydinh.getTenQuyDinh(),
                        quydinh.getKieu(),
                        quydinh.getGiaTri(),
                        quydinh.getTinhTrang(),
                        null
                    });
                }

            }
        });
    }

    public void refreshData(){
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                table.removeEditor();
                dtm.setRowCount(0);
                listQuydinhs = QuydinhBUS.getListQuyDinh();

                for (Quydinh quydinh : listQuydinhs) {

                    dtm.addRow(new Object[]{
                        quydinh.getIdQuyDinh(),
                        quydinh.getTenQuyDinh(),
                        quydinh.getKieu(),
                        quydinh.getGiaTri(),
                        quydinh.getTinhTrang(),
                        null
                    });
                }

            }
        });
    }
}
