/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.admin.quanlycb;

/**
 *
 * @author HAO
 */
public class SanBayTrungGianItemViewPane extends javax.swing.JPanel {

    /**
     * Creates new form SanBayTrungGianItemViewPane
     */
    public SanBayTrungGianItemViewPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sttLabel = new javax.swing.JLabel();
        STTLabel1 = new javax.swing.JLabel();

        setOpaque(false);

        sttLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sttLabel.setText("1.");

        STTLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        STTLabel1.setText("Hồ Chí Minh (HCM) - Việt Nam");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(sttLabel)
                .addGap(40, 40, 40)
                .addComponent(STTLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sttLabel)
                    .addComponent(STTLabel1))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setTitle(int index) {
        sttLabel.setText("" + index + ". ");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel STTLabel1;
    private javax.swing.JLabel sttLabel;
    // End of variables declaration//GEN-END:variables
}
