/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.admin.quanlycb;

import bus.SanbayBUS;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import pojos.Sanbay;

/**
 *
 * @author HAO
 */
public class SanBayTrungGianItemEditPane extends javax.swing.JPanel {

    private List<Sanbay> listSBTG;
    private List<String> listQG;
    /**
     * Creates new form SanBayTrungGianPane
     */
    public SanBayTrungGianItemEditPane() {
        initComponents();
        setModelForCbb();
        setEventForCbb();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        quocGiaSanBayTGCbb = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        maSanBayTGCbb = new javax.swing.JComboBox<>();
        titleLabel = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setOpaque(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Quốc gia: ");

        quocGiaSanBayTGCbb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        quocGiaSanBayTGCbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        quocGiaSanBayTGCbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quocGiaSanBayTGCbbActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Mã sân bay: ");

        maSanBayTGCbb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        maSanBayTGCbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        maSanBayTGCbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maSanBayTGCbbActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleLabel.setText("Sân bay 1");

        deleteButton.setBackground(new java.awt.Color(204, 0, 0));
        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/x.png"))); // NOI18N
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quocGiaSanBayTGCbb, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maSanBayTGCbb, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(quocGiaSanBayTGCbb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maSanBayTGCbb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addComponent(deleteButton))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void quocGiaSanBayTGCbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quocGiaSanBayTGCbbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quocGiaSanBayTGCbbActionPerformed

    private void maSanBayTGCbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maSanBayTGCbbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maSanBayTGCbbActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonActionPerformed


    public void setTitle(int index){
        titleLabel.setText("Sân bay trung gian " + index);
    }

    public JButton getDeleteButton() {
        return deleteButton;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> maSanBayTGCbb;
    private javax.swing.JComboBox<String> quocGiaSanBayTGCbb;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

    private void setModelForCbb() {

        listQG = SanbayBUS.getListQuocGias();
        DefaultComboBoxModel dcbQGSBTG = new DefaultComboBoxModel();
        for (String quocGia : listQG) {
            dcbQGSBTG.addElement(quocGia);
        }
        quocGiaSanBayTGCbb.setModel(dcbQGSBTG);

        DefaultComboBoxModel dcbSBDi = new DefaultComboBoxModel();
        maSanBayTGCbb.setModel(dcbSBDi);

        if (!listQG.isEmpty()) {

            listSBTG = SanbayBUS.getListSanbaysByQuocGia(listQG.get(0));
            for (Sanbay sanBayTG : listSBTG) {
                dcbSBDi.addElement(sanBayTG.getThanhPho() + " (" + sanBayTG.getMaSb() + ")");
            }

        }

    }

    private void setEventForCbb() {
        quocGiaSanBayTGCbb.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                listSBTG = SanbayBUS.getListSanbaysByQuocGia((String) quocGiaSanBayTGCbb.getSelectedItem());
                DefaultComboBoxModel dcbSBTG = (DefaultComboBoxModel) maSanBayTGCbb.getModel();
                dcbSBTG.removeAllElements();
                for (Sanbay sanBayTG : listSBTG) {
                    dcbSBTG.addElement(sanBayTG.getThanhPho() + " (" + sanBayTG.getMaSb() + ")");
                }
            }
        });

    }

    public String getMaCB(){
        return listSBTG.get(maSanBayTGCbb.getSelectedIndex()).getMaSb();
    }

    void fillUpData(String quocGia, String maSb) {
        for (int i = 0; i < listQG.size(); i++) {
            if (listQG.get(i).equals(quocGia)) {
                quocGiaSanBayTGCbb.setSelectedIndex(i);
            }
        }


        listSBTG = SanbayBUS.getListSanbaysByQuocGia(listQG.get(quocGiaSanBayTGCbb.getSelectedIndex()));
        int maSanBayTGCbbSelectedIndex = 1;

        DefaultComboBoxModel dcbSBTG = (DefaultComboBoxModel) maSanBayTGCbb.getModel();
        for (int i = 0; i < listSBTG.size(); i++) {
            if (listSBTG.get(i).getMaSb().equals(maSb)) {
                maSanBayTGCbbSelectedIndex = i;
            }
            dcbSBTG.addElement(listSBTG.get(i).getThanhPho() + " (" + listSBTG.get(i).getMaSb() + ")");

        }
        maSanBayTGCbb.setSelectedIndex(maSanBayTGCbbSelectedIndex);
    }
}
