/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.admin.quanlycb;

import bus.ChuyenbayBUS;
import bus.QuydinhBUS;
import bus.SanbayBUS;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javafx.util.Pair;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import pojos.Chuyenbay;
import pojos.Quydinh;
import pojos.Sanbay;
import util.ui.ImageIconUtil;

/**
 *
 * @author HAO
 */
public class ThemChuyenBayPane extends javax.swing.JPanel {

    private List<SanBayTrungGianItemEditPane> listSBTGItemPanes = new ArrayList<>();
    /**
     * Creates new form ThemChuyenBayPane
     */
    private QuanLyChuyenBayPane quanLyChuyenBayPane;

    private List<Sanbay> listSBDi;
    private List<Sanbay> listSBDen;
    private List<String> listQG;

    private Double thoiGianDungMin = 0d;
    private Double thoiGianDungMax = 10d;
    private Integer soSbTGMax = 50;

    public ThemChuyenBayPane(QuanLyChuyenBayPane quanLyChuyenBayPane) {

        this.quanLyChuyenBayPane = quanLyChuyenBayPane;
        initComponents();

        Quydinh thoiGianDungMinQd = QuydinhBUS.getQuydinh(4);
        Quydinh thoiGianDungMaxQd = QuydinhBUS.getQuydinh(5);
        Quydinh soSbTGMaxQd = QuydinhBUS.getQuydinh(3);

        try {
            thoiGianDungMin = thoiGianDungMinQd != null ? Double.parseDouble(thoiGianDungMinQd.getGiaTri()) : 0d;
            thoiGianDungMax = thoiGianDungMaxQd != null ? Double.parseDouble(thoiGianDungMaxQd.getGiaTri()) : 10d;
        } catch (NumberFormatException ex) {
            thoiGianDungMin = 0d;
            thoiGianDungMax = 10d;
        }

        try {
            soSbTGMax = soSbTGMaxQd != null ? Integer.parseInt(soSbTGMaxQd.getGiaTri()) : 50;
        } catch (NumberFormatException ex) {
            soSbTGMax = 50;
        }

        setModelForCbb();
        setEventForCbb();
        setEventForSLGheField();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePane = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(80, 0), new java.awt.Dimension(80, 0), new java.awt.Dimension(80, 0));
        backButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0));
        jLabel1 = new javax.swing.JLabel();
        filler15 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        submitButton = new javax.swing.JButton();
        filler16 = new javax.swing.Box.Filler(new java.awt.Dimension(80, 0), new java.awt.Dimension(80, 0), new java.awt.Dimension(80, 0));
        containerContentPane = new javax.swing.JPanel();
        contentPane = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        containerChuyenBayPane = new javax.swing.JPanel();
        chuyenBayPane = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0));
        jLabel2 = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0));
        maCBField = new javax.swing.JTextField();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(3000, 0));
        jLabel3 = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0));
        ngayKhoiHanhChooser = new com.toedter.calendar.JDateChooser();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0));
        gioKhoiHanhChooser = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        phutKhoiHanhChooser = new javax.swing.JSpinner();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(3000, 0));
        jLabel5 = new javax.swing.JLabel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0));
        thoiGianBayChooser = new javax.swing.JSpinner();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0));
        containerDetailsPane = new javax.swing.JPanel();
        hangVePane = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        soLuongGheH2Field = new javax.swing.JFormattedTextField();
        soLuongGheH3Field = new javax.swing.JFormattedTextField();
        giaVeH1Field = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        soLuongGheH1Field = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        giaVeH2Field = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        giaVeH3Field = new javax.swing.JFormattedTextField();
        soLuongGheLabel = new javax.swing.JLabel();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        sanBayPane = new javax.swing.JPanel();
        sanBayTGPane1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        maSanBayDiCbb = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        quocGiaSanBayDiCbb = new javax.swing.JComboBox<>();
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30));
        sanBayTGPane2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        quocGiaSanBayDenCbb = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        maSanBayDenCbb = new javax.swing.JComboBox<>();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        sanBayTGPane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sanBayTGInnerPane = new javax.swing.JPanel();
        filler14 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 40), new java.awt.Dimension(0, 40), new java.awt.Dimension(0, 40));
        themSBTGButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(250, 250, 250));
        setName("themCB"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        titlePane.setBackground(new java.awt.Color(255, 255, 255));
        titlePane.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        titlePane.setOpaque(false);
        titlePane.setPreferredSize(new java.awt.Dimension(643, 80));
        titlePane.setLayout(new javax.swing.BoxLayout(titlePane, javax.swing.BoxLayout.LINE_AXIS));
        titlePane.add(filler2);

        backButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/go_back.png"))); // NOI18N
        backButton.setText("Hủy");
        backButton.setMaximumSize(new java.awt.Dimension(125, 45));
        backButton.setPreferredSize(new java.awt.Dimension(125, 45));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        titlePane.add(backButton);
        titlePane.add(filler1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(56, 89, 98));
        jLabel1.setText("| Thêm chuyến bay");
        titlePane.add(jLabel1);
        titlePane.add(filler15);

        submitButton.setBackground(new java.awt.Color(140, 197, 66));
        submitButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Xác nhận");
        submitButton.setMaximumSize(new java.awt.Dimension(150, 50));
        submitButton.setMinimumSize(new java.awt.Dimension(150, 50));
        submitButton.setPreferredSize(new java.awt.Dimension(150, 40));
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        titlePane.add(submitButton);
        titlePane.add(filler16);

        add(titlePane, java.awt.BorderLayout.PAGE_START);

        containerContentPane.setBackground(new java.awt.Color(255, 255, 255));
        containerContentPane.setOpaque(false);
        containerContentPane.setLayout(new java.awt.BorderLayout());

        contentPane.setOpaque(false);
        contentPane.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(1650, 802));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        containerChuyenBayPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 0, 1, 0));
        containerChuyenBayPane.setMaximumSize(new java.awt.Dimension(32767, 150));
        containerChuyenBayPane.setOpaque(false);
        containerChuyenBayPane.setLayout(new javax.swing.BoxLayout(containerChuyenBayPane, javax.swing.BoxLayout.LINE_AXIS));

        chuyenBayPane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Chuyến bay", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(56, 89, 98))); // NOI18N
        chuyenBayPane.setMaximumSize(new java.awt.Dimension(2000, 150));
        chuyenBayPane.setMinimumSize(new java.awt.Dimension(32767, 150));
        chuyenBayPane.setName(""); // NOI18N
        chuyenBayPane.setOpaque(false);
        chuyenBayPane.setPreferredSize(new java.awt.Dimension(1600, 150));
        chuyenBayPane.setLayout(new javax.swing.BoxLayout(chuyenBayPane, javax.swing.BoxLayout.LINE_AXIS));
        chuyenBayPane.add(filler3);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Mã chuyến bay:");
        chuyenBayPane.add(jLabel2);
        chuyenBayPane.add(filler4);

        maCBField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        maCBField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10)));
        maCBField.setMaximumSize(new java.awt.Dimension(120, 40));
        maCBField.setPreferredSize(new java.awt.Dimension(120, 40));
        maCBField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maCBFieldActionPerformed(evt);
            }
        });
        chuyenBayPane.add(maCBField);
        chuyenBayPane.add(filler5);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Thời điểm khởi hành:");
        chuyenBayPane.add(jLabel3);
        chuyenBayPane.add(filler6);

        ngayKhoiHanhChooser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ngayKhoiHanhChooser.setMaximumSize(new java.awt.Dimension(150, 40));
        ngayKhoiHanhChooser.setPreferredSize(new java.awt.Dimension(150, 40));
        chuyenBayPane.add(ngayKhoiHanhChooser);
        chuyenBayPane.add(filler7);

        gioKhoiHanhChooser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gioKhoiHanhChooser.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));
        gioKhoiHanhChooser.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        gioKhoiHanhChooser.setMaximumSize(new java.awt.Dimension(85, 40));
        gioKhoiHanhChooser.setPreferredSize(new java.awt.Dimension(85, 40));
        chuyenBayPane.add(gioKhoiHanhChooser);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText(" : ");
        chuyenBayPane.add(jLabel4);

        phutKhoiHanhChooser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phutKhoiHanhChooser.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        phutKhoiHanhChooser.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        phutKhoiHanhChooser.setMaximumSize(new java.awt.Dimension(85, 40));
        phutKhoiHanhChooser.setPreferredSize(new java.awt.Dimension(85, 40));
        chuyenBayPane.add(phutKhoiHanhChooser);
        chuyenBayPane.add(filler8);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Thời gian bay:");
        chuyenBayPane.add(jLabel5);
        chuyenBayPane.add(filler9);

        thoiGianBayChooser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        thoiGianBayChooser.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 1.0f));
        thoiGianBayChooser.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        thoiGianBayChooser.setMaximumSize(new java.awt.Dimension(120, 40));
        thoiGianBayChooser.setPreferredSize(new java.awt.Dimension(120, 40));
        chuyenBayPane.add(thoiGianBayChooser);
        chuyenBayPane.add(filler10);

        containerChuyenBayPane.add(chuyenBayPane);

        jPanel2.add(containerChuyenBayPane);

        containerDetailsPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 0, 1, 0));
        containerDetailsPane.setMaximumSize(new java.awt.Dimension(3000, 3000));
        containerDetailsPane.setOpaque(false);
        containerDetailsPane.setLayout(new javax.swing.BoxLayout(containerDetailsPane, javax.swing.BoxLayout.LINE_AXIS));

        hangVePane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ghế", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(56, 89, 98))); // NOI18N
        hangVePane.setAlignmentY(0.0F);
        hangVePane.setMaximumSize(new java.awt.Dimension(550, 600));
        hangVePane.setMinimumSize(new java.awt.Dimension(550, 600));
        hangVePane.setName(""); // NOI18N
        hangVePane.setOpaque(false);
        hangVePane.setPreferredSize(new java.awt.Dimension(550, 600));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Số ghế:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dot.png"))); // NOI18N
        jLabel7.setText("   Số ghế hạng 1:");
        jLabel7.setIcon(ImageIconUtil.ResizeImage("src/main/resources/icon/dot.png", 15, 15));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dot.png"))); // NOI18N
        jLabel8.setText("   Số ghế hạng 2:");
        jLabel8.setIcon(ImageIconUtil.ResizeImage("src/main/resources/icon/dot.png", 15, 15));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dot.png"))); // NOI18N
        jLabel9.setText("   Số ghế hạng 3:");
        jLabel9.setIcon(ImageIconUtil.ResizeImage("src/main/resources/icon/dot.png", 15, 15));

        soLuongGheH2Field.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10)));
        soLuongGheH2Field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));
        soLuongGheH2Field.setText("0");
        soLuongGheH2Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        soLuongGheH2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soLuongGheH2FieldActionPerformed(evt);
            }
        });

        soLuongGheH3Field.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10)));
        soLuongGheH3Field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));
        soLuongGheH3Field.setText("0");
        soLuongGheH3Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        soLuongGheH3Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soLuongGheH3FieldActionPerformed(evt);
            }
        });

        giaVeH1Field.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10)));
        giaVeH1Field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));
        giaVeH1Field.setText("0");
        giaVeH1Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        giaVeH1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giaVeH1FieldActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Giá vé: ");

        soLuongGheH1Field.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10)));
        soLuongGheH1Field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));
        soLuongGheH1Field.setText("0");
        soLuongGheH1Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        soLuongGheH1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soLuongGheH1FieldActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Giá vé: ");

        giaVeH2Field.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10)));
        giaVeH2Field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));
        giaVeH2Field.setText("0");
        giaVeH2Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        giaVeH2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giaVeH2FieldActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Giá vé: ");

        giaVeH3Field.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10)));
        giaVeH3Field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));
        giaVeH3Field.setText("0");
        giaVeH3Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        giaVeH3Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giaVeH3FieldActionPerformed(evt);
            }
        });

        soLuongGheLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        soLuongGheLabel.setText("0");

        javax.swing.GroupLayout hangVePaneLayout = new javax.swing.GroupLayout(hangVePane);
        hangVePane.setLayout(hangVePaneLayout);
        hangVePaneLayout.setHorizontalGroup(
            hangVePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hangVePaneLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(hangVePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hangVePaneLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(44, 44, 44)
                        .addComponent(soLuongGheLabel))
                    .addGroup(hangVePaneLayout.createSequentialGroup()
                        .addGroup(hangVePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addGap(38, 38, 38)
                        .addGroup(hangVePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(soLuongGheH3Field, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(soLuongGheH2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(soLuongGheH1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(hangVePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(hangVePaneLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(giaVeH1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(hangVePaneLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(giaVeH2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(hangVePaneLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(giaVeH3Field, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hangVePaneLayout.setVerticalGroup(
            hangVePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hangVePaneLayout.createSequentialGroup()
                .addGroup(hangVePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hangVePaneLayout.createSequentialGroup()
                        .addGroup(hangVePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hangVePaneLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(hangVePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(soLuongGheLabel))
                                .addGap(84, 84, 84)
                                .addGroup(hangVePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(soLuongGheH1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(giaVeH1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(75, 75, 75)
                                .addGroup(hangVePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(giaVeH2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hangVePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(soLuongGheH2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(75, 75, 75)
                        .addComponent(giaVeH3Field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hangVePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(soLuongGheH3Field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        containerDetailsPane.add(hangVePane);
        containerDetailsPane.add(filler11);

        sanBayPane.setAlignmentY(0.0F);
        sanBayPane.setMaximumSize(new java.awt.Dimension(550, 600));
        sanBayPane.setMinimumSize(new java.awt.Dimension(550, 600));
        sanBayPane.setName(""); // NOI18N
        sanBayPane.setOpaque(false);
        sanBayPane.setPreferredSize(new java.awt.Dimension(550, 600));
        sanBayPane.setLayout(new javax.swing.BoxLayout(sanBayPane, javax.swing.BoxLayout.PAGE_AXIS));

        sanBayTGPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Sân bay đi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(56, 89, 98))); // NOI18N
        sanBayTGPane1.setMaximumSize(new java.awt.Dimension(550, 285));
        sanBayTGPane1.setMinimumSize(new java.awt.Dimension(550, 285));
        sanBayTGPane1.setName(""); // NOI18N
        sanBayTGPane1.setOpaque(false);
        sanBayTGPane1.setPreferredSize(new java.awt.Dimension(550, 285));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Quốc gia: ");

        maSanBayDiCbb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        maSanBayDiCbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        maSanBayDiCbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maSanBayDiCbbActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Mã sân bay: ");

        quocGiaSanBayDiCbb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        quocGiaSanBayDiCbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        quocGiaSanBayDiCbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quocGiaSanBayDiCbbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sanBayTGPane1Layout = new javax.swing.GroupLayout(sanBayTGPane1);
        sanBayTGPane1.setLayout(sanBayTGPane1Layout);
        sanBayTGPane1Layout.setHorizontalGroup(
            sanBayTGPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sanBayTGPane1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(sanBayTGPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(sanBayTGPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(maSanBayDiCbb, 0, 384, Short.MAX_VALUE)
                    .addComponent(quocGiaSanBayDiCbb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sanBayTGPane1Layout.setVerticalGroup(
            sanBayTGPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sanBayTGPane1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(sanBayTGPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(quocGiaSanBayDiCbb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(sanBayTGPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(maSanBayDiCbb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        sanBayPane.add(sanBayTGPane1);
        sanBayPane.add(filler13);

        sanBayTGPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Sân bay đến", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(56, 89, 98))); // NOI18N
        sanBayTGPane2.setMaximumSize(new java.awt.Dimension(550, 285));
        sanBayTGPane2.setMinimumSize(new java.awt.Dimension(550, 285));
        sanBayTGPane2.setName(""); // NOI18N
        sanBayTGPane2.setOpaque(false);
        sanBayTGPane2.setPreferredSize(new java.awt.Dimension(550, 285));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Quốc gia: ");

        quocGiaSanBayDenCbb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        quocGiaSanBayDenCbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        quocGiaSanBayDenCbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quocGiaSanBayDenCbbActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Mã sân bay: ");

        maSanBayDenCbb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        maSanBayDenCbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        maSanBayDenCbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maSanBayDenCbbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sanBayTGPane2Layout = new javax.swing.GroupLayout(sanBayTGPane2);
        sanBayTGPane2.setLayout(sanBayTGPane2Layout);
        sanBayTGPane2Layout.setHorizontalGroup(
            sanBayTGPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sanBayTGPane2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(sanBayTGPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(sanBayTGPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(maSanBayDenCbb, 0, 384, Short.MAX_VALUE)
                    .addComponent(quocGiaSanBayDenCbb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sanBayTGPane2Layout.setVerticalGroup(
            sanBayTGPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sanBayTGPane2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(sanBayTGPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(quocGiaSanBayDenCbb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(sanBayTGPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(maSanBayDenCbb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        sanBayPane.add(sanBayTGPane2);

        containerDetailsPane.add(sanBayPane);
        containerDetailsPane.add(filler12);

        sanBayTGPane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Sân bay trung gian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(56, 89, 98))); // NOI18N
        sanBayTGPane.setAlignmentY(0.0F);
        sanBayTGPane.setMaximumSize(new java.awt.Dimension(550, 600));
        sanBayTGPane.setMinimumSize(new java.awt.Dimension(550, 600));
        sanBayTGPane.setName(""); // NOI18N
        sanBayTGPane.setOpaque(false);
        sanBayTGPane.setPreferredSize(new java.awt.Dimension(550, 600));
        sanBayTGPane.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(250, 250, 250));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        sanBayTGInnerPane.setBackground(new java.awt.Color(250, 250, 250));
        sanBayTGInnerPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 15));
        sanBayTGInnerPane.setLayout(new javax.swing.BoxLayout(sanBayTGInnerPane, javax.swing.BoxLayout.PAGE_AXIS));
        sanBayTGInnerPane.add(filler14);

        themSBTGButton.setBackground(new java.awt.Color(153, 153, 0));
        themSBTGButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        themSBTGButton.setForeground(new java.awt.Color(255, 255, 255));
        themSBTGButton.setText("Thêm sân bay trung gian");
        themSBTGButton.setMaximumSize(new java.awt.Dimension(520, 50));
        themSBTGButton.setMinimumSize(new java.awt.Dimension(520, 40));
        themSBTGButton.setPreferredSize(new java.awt.Dimension(520, 50));
        themSBTGButton.setIcon(ImageIconUtil.ResizeImage("src/main/resources/icon/plus_math.png", 15, 15));
        themSBTGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themSBTGButtonActionPerformed(evt);
            }
        });
        sanBayTGInnerPane.add(themSBTGButton);

        jScrollPane1.setViewportView(sanBayTGInnerPane);

        jScrollPane1.getVerticalScrollBar().setUnitIncrement(20);

        sanBayTGPane.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        containerDetailsPane.add(sanBayTGPane);

        jPanel2.add(containerDetailsPane);

        contentPane.add(jPanel2, java.awt.BorderLayout.CENTER);

        containerContentPane.add(contentPane, java.awt.BorderLayout.CENTER);

        jPanel7.setOpaque(false);
        jPanel7.setPreferredSize(new java.awt.Dimension(80, 100));
        containerContentPane.add(jPanel7, java.awt.BorderLayout.WEST);

        jPanel8.setOpaque(false);
        jPanel8.setPreferredSize(new java.awt.Dimension(80, 100));
        containerContentPane.add(jPanel8, java.awt.BorderLayout.EAST);

        add(containerContentPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        quanLyChuyenBayPane.getParentPane().remove(this);
    }//GEN-LAST:event_backButtonActionPerformed

    private void maCBFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maCBFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maCBFieldActionPerformed

    private void soLuongGheH2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soLuongGheH2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soLuongGheH2FieldActionPerformed

    private void soLuongGheH3FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soLuongGheH3FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soLuongGheH3FieldActionPerformed

    private void giaVeH1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giaVeH1FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giaVeH1FieldActionPerformed

    private void soLuongGheH1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soLuongGheH1FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soLuongGheH1FieldActionPerformed

    private void giaVeH2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giaVeH2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giaVeH2FieldActionPerformed

    private void giaVeH3FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giaVeH3FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giaVeH3FieldActionPerformed

    private void maSanBayDiCbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maSanBayDiCbbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maSanBayDiCbbActionPerformed

    private void quocGiaSanBayDiCbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quocGiaSanBayDiCbbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quocGiaSanBayDiCbbActionPerformed

    private void quocGiaSanBayDenCbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quocGiaSanBayDenCbbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quocGiaSanBayDenCbbActionPerformed

    private void maSanBayDenCbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maSanBayDenCbbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maSanBayDenCbbActionPerformed

    private void themSBTGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themSBTGButtonActionPerformed
        SanBayTrungGianItemEditPane sbtgItemPane = new SanBayTrungGianItemEditPane(thoiGianDungMin, thoiGianDungMax);
        sbtgItemPane.setMaximumSize(new Dimension(520, 240));
        sbtgItemPane.setPreferredSize(new Dimension(520, 240));
        sbtgItemPane.setAlignmentX(0);
        sbtgItemPane.setTitle(listSBTGItemPanes.size() + 1);

        sanBayTGInnerPane.add(sbtgItemPane, sanBayTGInnerPane.getComponentCount() - 1);
        listSBTGItemPanes.add(sbtgItemPane);
        if (listSBTGItemPanes.size() >= soSbTGMax){
            themSBTGButton.setEnabled(false);
        }

        sbtgItemPane.getDeleteButton().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                sanBayTGInnerPane.remove(sbtgItemPane);

                int i;
                for (i = 0; i < listSBTGItemPanes.size(); i++) {
                    if (listSBTGItemPanes.get(i) == sbtgItemPane) {
                        listSBTGItemPanes.remove(i);
                        break;
                    }
                }
                for (; i < listSBTGItemPanes.size(); i++){
                    listSBTGItemPanes.get(i).setTitle(i + 1);
                }

                if (listSBTGItemPanes.size() < soSbTGMax && !themSBTGButton.isEnabled()) {
                    themSBTGButton.setEnabled(true);
                }

                sanBayTGInnerPane.invalidate();
                sanBayTGInnerPane.revalidate();
                sanBayTGInnerPane.repaint();

            }
        });

        sanBayTGInnerPane.invalidate();
        sanBayTGInnerPane.revalidate();
        sanBayTGInnerPane.repaint();

    }//GEN-LAST:event_themSBTGButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed

        Sanbay sanbayDi = SanbayBUS.getSanbayById(listSBDi.get(maSanBayDiCbb.getSelectedIndex()).getMaSb());
        Sanbay sanbayDen = SanbayBUS.getSanbayById(listSBDen.get(maSanBayDenCbb.getSelectedIndex()).getMaSb());

        String maCB = maCBField.getText();
        if (maCB.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin");
            return;
        }

        Chuyenbay checkChuyenbay = ChuyenbayBUS.getChuyenBayByID(maCB);
        if (checkChuyenbay != null){
            JOptionPane.showMessageDialog(null, "Đã có chuyến bay với mã chuyến bay là " + maCB + " trong cơ sở dữ liệu!");
            return;
        }

        Date ngayKhoiHanh = ngayKhoiHanhChooser.getDate();

        if (ngayKhoiHanh == null) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin");
            return;
        }

        ngayKhoiHanh.setHours((Integer) gioKhoiHanhChooser.getValue());
        ngayKhoiHanh.setMinutes((Integer) phutKhoiHanhChooser.getValue());

        Float thoiGianBay = (Float) thoiGianBayChooser.getValue();

        Chuyenbay newCB = new Chuyenbay(maCB, sanbayDi, sanbayDen, ngayKhoiHanh, thoiGianBay, "Chưa khởi hành");

        List<String> listMaSBTG = new ArrayList<>();
        List<Double> listThoiGianDung = new ArrayList<>();
        for (int i = 0; i < listSBTGItemPanes.size(); i++){
            String maSBTG = listSBTGItemPanes.get(i).getMaCB();
            if (listMaSBTG.contains(maSBTG)){
                JOptionPane.showMessageDialog(null, "Các sân bay trung gian không thể trùng nhau!");
                return;
            }
            listMaSBTG.add(maSBTG);
            listThoiGianDung.add(listSBTGItemPanes.get(i).getThoiGianDung());
        }

        List<Integer> listSoLuongVeTheoHang = new ArrayList<>();
        listSoLuongVeTheoHang.add(Integer.parseInt(soLuongGheH1Field.getText()));
        listSoLuongVeTheoHang.add(Integer.parseInt(soLuongGheH2Field.getText()));
        listSoLuongVeTheoHang.add(Integer.parseInt(soLuongGheH3Field.getText()));

        List<Double> listGiaVeTheoHang = new ArrayList<>();
        listGiaVeTheoHang.add(Double.parseDouble(giaVeH1Field.getText()));
        listGiaVeTheoHang.add(Double.parseDouble(giaVeH2Field.getText()));
        listGiaVeTheoHang.add(Double.parseDouble(giaVeH3Field.getText()));

        ChuyenbayBUS.themChuyenBay(newCB, listMaSBTG, listThoiGianDung, listSoLuongVeTheoHang, listGiaVeTheoHang);

        quanLyChuyenBayPane.getParentPane().remove(this);
        quanLyChuyenBayPane.proceedToFilter();

        JOptionPane.showMessageDialog(null, "Đã thêm chuyến bay " + maCB);
    }//GEN-LAST:event_submitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel chuyenBayPane;
    private javax.swing.JPanel containerChuyenBayPane;
    private javax.swing.JPanel containerContentPane;
    private javax.swing.JPanel containerDetailsPane;
    private javax.swing.JPanel contentPane;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler14;
    private javax.swing.Box.Filler filler15;
    private javax.swing.Box.Filler filler16;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JFormattedTextField giaVeH1Field;
    private javax.swing.JFormattedTextField giaVeH2Field;
    private javax.swing.JFormattedTextField giaVeH3Field;
    private javax.swing.JSpinner gioKhoiHanhChooser;
    private javax.swing.JPanel hangVePane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField maCBField;
    private javax.swing.JComboBox<String> maSanBayDenCbb;
    private javax.swing.JComboBox<String> maSanBayDiCbb;
    private com.toedter.calendar.JDateChooser ngayKhoiHanhChooser;
    private javax.swing.JSpinner phutKhoiHanhChooser;
    private javax.swing.JComboBox<String> quocGiaSanBayDenCbb;
    private javax.swing.JComboBox<String> quocGiaSanBayDiCbb;
    private javax.swing.JPanel sanBayPane;
    private javax.swing.JPanel sanBayTGInnerPane;
    private javax.swing.JPanel sanBayTGPane;
    private javax.swing.JPanel sanBayTGPane1;
    private javax.swing.JPanel sanBayTGPane2;
    private javax.swing.JFormattedTextField soLuongGheH1Field;
    private javax.swing.JFormattedTextField soLuongGheH2Field;
    private javax.swing.JFormattedTextField soLuongGheH3Field;
    private javax.swing.JLabel soLuongGheLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JButton themSBTGButton;
    private javax.swing.JSpinner thoiGianBayChooser;
    private javax.swing.JPanel titlePane;
    // End of variables declaration//GEN-END:variables

    private void setModelForCbb() {


        listQG = SanbayBUS.getListQuocGias();
        DefaultComboBoxModel dcbQGSBDi = new DefaultComboBoxModel();
        for (String quocGia : listQG) {
            dcbQGSBDi.addElement(quocGia);
        }
        quocGiaSanBayDiCbb.setModel(dcbQGSBDi);

        DefaultComboBoxModel dcbQGSBDen = new DefaultComboBoxModel();
        for (String quocGia : listQG) {
            dcbQGSBDen.addElement(quocGia);
        }
        quocGiaSanBayDenCbb.setModel(dcbQGSBDen);

        DefaultComboBoxModel dcbSBDi = new DefaultComboBoxModel();
        maSanBayDiCbb.setModel(dcbSBDi);
        DefaultComboBoxModel dcbSBDen = new DefaultComboBoxModel();
        maSanBayDenCbb.setModel(dcbSBDen);

        if (!listQG.isEmpty()) {

            listSBDi = SanbayBUS.getListSanbaysByQuocGia(listQG.get(0));
            for (Sanbay sanBayDi : listSBDi) {
                dcbSBDi.addElement(sanBayDi.getThanhPho() + " (" + sanBayDi.getMaSb() + ")");
            }

            listSBDen = SanbayBUS.getListSanbaysByQuocGia(listQG.get(0));
            for (Sanbay sanBayDen : listSBDen) {
                dcbSBDen.addElement(sanBayDen.getThanhPho() + " (" + sanBayDen.getMaSb() + ")");
            }
        }

    }

    private void setEventForCbb() {
        quocGiaSanBayDiCbb.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                listSBDi = SanbayBUS.getListSanbaysByQuocGia((String) quocGiaSanBayDiCbb.getSelectedItem());
                DefaultComboBoxModel dcbSBDi = (DefaultComboBoxModel) maSanBayDiCbb.getModel();
                dcbSBDi.removeAllElements();
                for (Sanbay sanBayDi : listSBDi) {
                    dcbSBDi.addElement(sanBayDi.getThanhPho() + " (" + sanBayDi.getMaSb() + ")");
                }
            }
        });

        quocGiaSanBayDenCbb.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                listSBDen = SanbayBUS.getListSanbaysByQuocGia((String) quocGiaSanBayDenCbb.getSelectedItem());
                DefaultComboBoxModel dcbSBDen = (DefaultComboBoxModel) maSanBayDenCbb.getModel();
                dcbSBDen.removeAllElements();
                for (Sanbay sanBayDen : listSBDen) {
                    dcbSBDen.addElement(sanBayDen.getThanhPho() + " (" + sanBayDen.getMaSb() + ")");
                }
            }
        });
    }

    private void setEventForSLGheField() {
        soLuongGheH1Field.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {

            }

            @Override
            public void focusLost(FocusEvent e) {
                Integer soLuongH1 = 0;
                try {
                    soLuongH1 = Integer.parseInt(soLuongGheH1Field.getText());
                } catch (NumberFormatException ex) {
                    soLuongH1 = 0;
                    soLuongGheH1Field.setText("0");
                } finally {
                    Integer soLuongH2 = Integer.parseInt(soLuongGheH2Field.getText());
                    Integer soLuongH3 = Integer.parseInt(soLuongGheH3Field.getText());

                    soLuongGheLabel.setText((soLuongH1 + soLuongH2 + soLuongH3) + "");
                }
            }
        });

        soLuongGheH2Field.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {

            }

            @Override
            public void focusLost(FocusEvent e) {
                Integer soLuongH2 = 0;
                try {
                    soLuongH2 = Integer.parseInt(soLuongGheH2Field.getText());
                } catch (NumberFormatException ex) {
                    soLuongH2 = 0;
                    soLuongGheH2Field.setText("0");
                } finally {
                    Integer soLuongH1 = Integer.parseInt(soLuongGheH1Field.getText());
                    Integer soLuongH3 = Integer.parseInt(soLuongGheH3Field.getText());

                    soLuongGheLabel.setText((soLuongH1 + soLuongH2 + soLuongH3) + "");
                }
            }
        });

        soLuongGheH3Field.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {

            }

            @Override
            public void focusLost(FocusEvent e) {
                Integer soLuongH3 = 0;
                try {
                    soLuongH3 = Integer.parseInt(soLuongGheH3Field.getText());
                } catch (NumberFormatException ex) {
                    soLuongH3 = 0;
                    soLuongGheH3Field.setText("0");
                } finally {
                    Integer soLuongH1 = Integer.parseInt(soLuongGheH1Field.getText());
                    Integer soLuongH2 = Integer.parseInt(soLuongGheH2Field.getText());

                    soLuongGheLabel.setText((soLuongH1 + soLuongH2 + soLuongH3) + "");
                }
            }
        });
    }
}
