/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui.user.tracuucb.ketqua;

import daos.HangveDAO;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Iterator;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;
import pojos.Chuyenbay;
import pojos.Giahangvetheocb;
import pojos.Sanbaytrunggian;
import ui.user.MainForUser;

/**
 *
 * @author DELL
 */
public class FlightPanel extends javax.swing.JPanel {

    /** Creates new form FightPanel */
    float thoigianbay = 0;
    Chuyenbay cb;
    int sl;
    String mahangve;
    public FlightPanel(Chuyenbay cb, int sl, String mahangve) {
        initComponents();
        
        this.cb = cb;
        this.sl = sl;
        this.mahangve = mahangve;
        
        jlbSBDi.setText(cb.getSanbaydi().getThanhPho() + " (" + cb.getSanbaydi().getMaSb() + ")");
        jlbSBDen.setText(cb.getSanbayden().getThanhPho() + " (" + cb.getSanbayden().getMaSb() + ")");
        
        int sodiemdung = 0;
        if(!cb.getSanbaytrunggians().isEmpty())
            sodiemdung = cb.getSanbaytrunggians().size();
        
        if(sodiemdung == 0)
            jlbSoDiemDung.setText("Bay thẳng");
        else
            jlbSoDiemDung.setText(String.format("%d điểm dừng",sodiemdung));
        
        DateFormat df = new SimpleDateFormat("HH:mm");
        String timeStart = df.format(cb.getNgayKhoiHanh());
        jlbTimeStart.setText(timeStart);
        
        float time = cb.getThoiGianBay();
        Iterator<Sanbaytrunggian> tgs = cb.getSanbaytrunggians().iterator();
        
        while(tgs.hasNext()){
            time+=tgs.next().getThoiGianDung();
        }
        thoigianbay = time;
        time *= 60; 
        //JOptionPane.showMessageDialog(null, time);
        String timeEnd = df.format(new Date(cb.getNgayKhoiHanh().getTime() + TimeUnit.MINUTES.toMillis((long) time)));
        
        jlbTimeEnd.setText(timeEnd);
        
        String tenhv = HangveDAO.getTicketLevelName(mahangve);
        
        jlbHangVe.setText(tenhv);
        
        Iterator<Giahangvetheocb> tgs1 = cb.getGiahangvetheocbs().iterator();
        
        while(tgs1.hasNext()){
            Giahangvetheocb giahv = tgs1.next();
            if(giahv.getHangve().getMaHangVe().equalsIgnoreCase(mahangve)){
                jlbGia.setText(String.format("%,.0f",giahv.getGiaHienTai()));
            }       
        }
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel8 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jlbSBDi = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jlbTimeStart = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jlbSBDen = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jlbTimeEnd = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jlbSoDiemDung = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jlbHangVe = new javax.swing.JLabel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0));
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jlbGia = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        jLabel8 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        btnChon = new javax.swing.JButton();
        filler17 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        setMaximumSize(new java.awt.Dimension(1000, 120));
        setMinimumSize(new java.awt.Dimension(500, 120));
        setPreferredSize(new java.awt.Dimension(400, 120));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
        add(filler6);

        jPanel8.setMaximumSize(new java.awt.Dimension(200, 90));
        jPanel8.setMinimumSize(new java.awt.Dimension(200, 90));
        jPanel8.setPreferredSize(new java.awt.Dimension(200, 90));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setMaximumSize(new java.awt.Dimension(200, 40));
        jPanel3.setMinimumSize(new java.awt.Dimension(200, 40));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jlbSBDi.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlbSBDi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/plane_takeoff.png"))); // NOI18N
        jlbSBDi.setText("Hà nội (HAN)");
        jlbSBDi.setMaximumSize(new java.awt.Dimension(200, 40));
        jlbSBDi.setMinimumSize(new java.awt.Dimension(200, 40));
        jlbSBDi.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(jlbSBDi);

        jPanel8.add(jPanel3);

        jPanel5.setMaximumSize(new java.awt.Dimension(200, 40));
        jPanel5.setMinimumSize(new java.awt.Dimension(200, 40));
        jPanel5.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jlbTimeStart.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlbTimeStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clock.png"))); // NOI18N
        jlbTimeStart.setText("07:00");
        jlbTimeStart.setAlignmentY(0.0F);
        jlbTimeStart.setMaximumSize(new java.awt.Dimension(150, 35));
        jlbTimeStart.setMinimumSize(new java.awt.Dimension(150, 35));
        jlbTimeStart.setPreferredSize(new java.awt.Dimension(150, 35));
        jPanel5.add(jlbTimeStart);

        jPanel8.add(jPanel5);

        add(jPanel8);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/flight.png"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(60, 40));
        jLabel7.setMinimumSize(new java.awt.Dimension(60, 40));
        jLabel7.setPreferredSize(new java.awt.Dimension(60, 40));
        add(jLabel7);

        jPanel12.setMaximumSize(new java.awt.Dimension(250, 90));
        jPanel12.setMinimumSize(new java.awt.Dimension(250, 90));
        jPanel12.setPreferredSize(new java.awt.Dimension(200, 90));
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.Y_AXIS));

        jPanel13.setMaximumSize(new java.awt.Dimension(200, 40));
        jPanel13.setMinimumSize(new java.awt.Dimension(200, 40));
        jPanel13.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jlbSBDen.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlbSBDen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/plane_landing.png"))); // NOI18N
        jlbSBDen.setText("TPHCM (SGN)");
        jlbSBDen.setMaximumSize(new java.awt.Dimension(200, 40));
        jlbSBDen.setMinimumSize(new java.awt.Dimension(200, 40));
        jlbSBDen.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel13.add(jlbSBDen);

        jPanel12.add(jPanel13);

        jPanel14.setMaximumSize(new java.awt.Dimension(200, 40));
        jPanel14.setMinimumSize(new java.awt.Dimension(200, 40));
        jPanel14.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jlbTimeEnd.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlbTimeEnd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clock.png"))); // NOI18N
        jlbTimeEnd.setText("09:00");
        jlbTimeEnd.setAlignmentY(0.0F);
        jlbTimeEnd.setMaximumSize(new java.awt.Dimension(150, 35));
        jlbTimeEnd.setMinimumSize(new java.awt.Dimension(150, 35));
        jlbTimeEnd.setPreferredSize(new java.awt.Dimension(150, 35));
        jPanel14.add(jlbTimeEnd);

        jPanel12.add(jPanel14);

        add(jPanel12);

        jPanel9.setMaximumSize(new java.awt.Dimension(150, 90));
        jPanel9.setMinimumSize(new java.awt.Dimension(150, 90));
        jPanel9.setPreferredSize(new java.awt.Dimension(150, 90));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.Y_AXIS));

        jPanel10.setMaximumSize(new java.awt.Dimension(150, 40));
        jPanel10.setMinimumSize(new java.awt.Dimension(150, 40));
        jPanel10.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jlbSoDiemDung.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlbSoDiemDung.setText("Bay thẳng");
        jlbSoDiemDung.setMaximumSize(new java.awt.Dimension(150, 40));
        jlbSoDiemDung.setMinimumSize(new java.awt.Dimension(150, 40));
        jlbSoDiemDung.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanel10.add(jlbSoDiemDung);

        jPanel9.add(jPanel10);

        jPanel18.setMaximumSize(new java.awt.Dimension(200, 40));
        jPanel18.setMinimumSize(new java.awt.Dimension(200, 40));
        jPanel18.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel18.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jlbHangVe.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlbHangVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/seat_level.png"))); // NOI18N
        jlbHangVe.setText("Phổ thông");
        jlbHangVe.setMaximumSize(new java.awt.Dimension(200, 40));
        jlbHangVe.setMinimumSize(new java.awt.Dimension(200, 40));
        jlbHangVe.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel18.add(jlbHangVe);

        jPanel9.add(jPanel18);

        add(jPanel9);
        add(filler7);

        jPanel15.setMaximumSize(new java.awt.Dimension(200, 90));
        jPanel15.setMinimumSize(new java.awt.Dimension(200, 90));
        jPanel15.setPreferredSize(new java.awt.Dimension(200, 90));
        jPanel15.setLayout(new javax.swing.BoxLayout(jPanel15, javax.swing.BoxLayout.Y_AXIS));

        jPanel16.setMaximumSize(new java.awt.Dimension(200, 40));
        jPanel16.setMinimumSize(new java.awt.Dimension(200, 40));
        jPanel16.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel16.setLayout(new javax.swing.BoxLayout(jPanel16, javax.swing.BoxLayout.LINE_AXIS));

        jlbGia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbGia.setForeground(new java.awt.Color(255, 0, 0));
        jlbGia.setText("500.000");
        jPanel16.add(jlbGia);
        jPanel16.add(filler3);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("VND/Khách");
        jLabel8.setMaximumSize(new java.awt.Dimension(200, 40));
        jLabel8.setMinimumSize(new java.awt.Dimension(200, 40));
        jLabel8.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel16.add(jLabel8);

        jPanel15.add(jPanel16);

        jPanel17.setMaximumSize(new java.awt.Dimension(200, 40));
        jPanel17.setMinimumSize(new java.awt.Dimension(200, 40));
        jPanel17.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel17.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        btnChon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnChon.setText("Chọn");
        btnChon.setMaximumSize(new java.awt.Dimension(100, 40));
        btnChon.setMinimumSize(new java.awt.Dimension(100, 40));
        btnChon.setPreferredSize(new java.awt.Dimension(100, 40));
        btnChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonActionPerformed(evt);
            }
        });
        jPanel17.add(btnChon);

        jPanel15.add(jPanel17);

        add(jPanel15);
        add(filler17);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonActionPerformed
        MainForUser.getInstance().getTraCuuPane().changeLayout(new ChiTietVeCBPanel(cb,sl,mahangve),"chitiet");
    }//GEN-LAST:event_btnChonActionPerformed

    public String getSoDiemDung(){
        return jlbSoDiemDung.getText();
    }
    
    public String getTimeStart(){
        return jlbTimeStart.getText();
    }
    
    public String getTimeEnd(){
        return jlbTimeEnd.getText();
    }
    
    public String getGia(){
        return jlbGia.getText().replaceAll(",","");
    }
    
    public float getThoiGianBay(){
        return thoigianbay;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChon;
    private javax.swing.Box.Filler filler17;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel jlbGia;
    private javax.swing.JLabel jlbHangVe;
    private javax.swing.JLabel jlbSBDen;
    private javax.swing.JLabel jlbSBDi;
    private javax.swing.JLabel jlbSoDiemDung;
    private javax.swing.JLabel jlbTimeEnd;
    private javax.swing.JLabel jlbTimeStart;
    // End of variables declaration//GEN-END:variables

}
