/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.admin.quanlynhanvien;

import bus.NhanvienBUS;
import bus.TaikhoanBUS;
import ui.admin.quanlycb.*;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import pojos.Nhanvien;
import pojos.Taikhoan;
import util.ui.ImageIconUtil;

/**
 *
 * @author HAO
 */
public class ThemNhanVienPane extends javax.swing.JPanel {

    private List<SanBayTrungGianItemEditPane> listSBTGItemPanes = new ArrayList<>();
    /**
     * Creates new form EditChuyenBayPane
     */
    private QuanLyNhanVienPane quanLyNhanVienPane;

    public ThemNhanVienPane(QuanLyNhanVienPane rootPane) {
        this.quanLyNhanVienPane = rootPane;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePane = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(80, 0), new java.awt.Dimension(80, 0), new java.awt.Dimension(80, 0));
        backButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0));
        jLabel1 = new javax.swing.JLabel();
        filler15 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        submitButton = new javax.swing.JButton();
        filler16 = new javax.swing.Box.Filler(new java.awt.Dimension(80, 0), new java.awt.Dimension(80, 0), new java.awt.Dimension(80, 0));
        containerContentPane = new javax.swing.JPanel();
        contentPane = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        hoTenField = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tenDangNhapFeild = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        ngaySinhChooser = new com.toedter.calendar.JDateChooser();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        sdtField = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        cmndFeild = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        emailFeild = new javax.swing.JTextField();
        gioiTinhCbb = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setName("themNV"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        titlePane.setBackground(new java.awt.Color(255, 255, 255));
        titlePane.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        titlePane.setOpaque(false);
        titlePane.setPreferredSize(new java.awt.Dimension(643, 80));
        titlePane.setLayout(new javax.swing.BoxLayout(titlePane, javax.swing.BoxLayout.LINE_AXIS));
        titlePane.add(filler2);

        backButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/go_back.png"))); // NOI18N
        backButton.setText("Hủy");
        backButton.setMaximumSize(new java.awt.Dimension(125, 45));
        backButton.setPreferredSize(new java.awt.Dimension(125, 45));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        titlePane.add(backButton);
        titlePane.add(filler1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(56, 89, 98));
        jLabel1.setText("| Thêm nhân viên");
        titlePane.add(jLabel1);
        titlePane.add(filler15);

        submitButton.setBackground(new java.awt.Color(140, 197, 66));
        submitButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Xác nhận");
        submitButton.setMaximumSize(new java.awt.Dimension(150, 50));
        submitButton.setMinimumSize(new java.awt.Dimension(150, 50));
        submitButton.setPreferredSize(new java.awt.Dimension(150, 40));
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        titlePane.add(submitButton);
        titlePane.add(filler16);

        add(titlePane, java.awt.BorderLayout.PAGE_START);

        containerContentPane.setBackground(new java.awt.Color(255, 255, 255));
        containerContentPane.setOpaque(false);
        containerContentPane.setLayout(new java.awt.BorderLayout());

        contentPane.setBackground(new java.awt.Color(255, 255, 255));
        contentPane.setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(56, 89, 98));
        jLabel24.setText("Họ Tên: ");

        hoTenField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(56, 89, 98));
        jLabel25.setText("Tên đăng nhập:");

        tenDangNhapFeild.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(56, 89, 98));
        jLabel26.setText("Ngày sinh: ");

        ngaySinhChooser.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(56, 89, 98));
        jLabel27.setText("Giới tính:");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(56, 89, 98));
        jLabel28.setText("Số điện thoại: ");

        sdtField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(56, 89, 98));
        jLabel29.setText("Số CMND:");

        cmndFeild.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(56, 89, 98));
        jLabel30.setText("Email:");

        emailFeild.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        emailFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFeildActionPerformed(evt);
            }
        });

        gioiTinhCbb.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        gioiTinhCbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel28)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hoTenField, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sdtField, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ngaySinhChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(138, 138, 138)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmndFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel27))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gioiTinhCbb, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tenDangNhapFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(101, 101, 101)
                        .addComponent(emailFeild)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(hoTenField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(tenDangNhapFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ngaySinhChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(jLabel26)))
                    .addComponent(gioiTinhCbb, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(sdtField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(cmndFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(emailFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contentPaneLayout = new javax.swing.GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        containerContentPane.add(contentPane, java.awt.BorderLayout.CENTER);

        jPanel7.setOpaque(false);
        jPanel7.setPreferredSize(new java.awt.Dimension(200, 100));
        containerContentPane.add(jPanel7, java.awt.BorderLayout.WEST);

        jPanel8.setOpaque(false);
        jPanel8.setPreferredSize(new java.awt.Dimension(200, 100));
        containerContentPane.add(jPanel8, java.awt.BorderLayout.EAST);

        add(containerContentPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        quanLyNhanVienPane.getParentPane().remove(this);
    }//GEN-LAST:event_backButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed


        String hoTen = hoTenField.getText();
        String tenDangNhap = tenDangNhapFeild.getText();
        Date ngaySinh = ngaySinhChooser.getDate();
        String gioiTinh = (String) gioiTinhCbb.getSelectedItem();
        String sdt = sdtField.getText();
        String cmnd = cmndFeild.getText();
        String email = emailFeild.getText();

        if (hoTen.isEmpty() || tenDangNhap.isEmpty() || ngaySinh == null || sdt.isEmpty() || cmnd.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin");
            return;
        }

        int id = TaikhoanBUS.checkAccount(tenDangNhap);
        if (id != 0) {
            JOptionPane.showMessageDialog(null, "Đã tồn tại tên đăng nhập " + tenDangNhap);
            return;
        }

        Nhanvien nv = new Nhanvien(hoTen, gioiTinh, ngaySinh, sdt, cmnd, email, tenDangNhap);
        Taikhoan taikhoan = new Taikhoan(nv, tenDangNhap, "12345678");
        nv.setTaikhoan(taikhoan);

        NhanvienBUS.themOrUpdateNhanvien(nv);

        quanLyNhanVienPane.proceedToFilter();
        quanLyNhanVienPane.getParentPane().remove(this);

        JOptionPane.showMessageDialog(null, "Đã thêm nhân viên " + hoTen);

    }//GEN-LAST:event_submitButtonActionPerformed

    private void emailFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFeildActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField cmndFeild;
    private javax.swing.JPanel containerContentPane;
    private javax.swing.JPanel contentPane;
    private javax.swing.JTextField emailFeild;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler15;
    private javax.swing.Box.Filler filler16;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JComboBox<String> gioiTinhCbb;
    private javax.swing.JTextField hoTenField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private com.toedter.calendar.JDateChooser ngaySinhChooser;
    private javax.swing.JTextField sdtField;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField tenDangNhapFeild;
    private javax.swing.JPanel titlePane;
    // End of variables declaration//GEN-END:variables
}
