/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.user.tracuucb;

import java.awt.CardLayout;
import javax.swing.JPanel;
import ui.user.tracuucb.ketqua.ChiTietVeCBPanel;

/**
 *
 * @author HAO
 */
public class TraCuuChuyenBayPane extends javax.swing.JPanel {

    /**
     * Creates new form TraCuuChuyenBay
     */
    CardLayout cardLayout;
    private JPanel jpnTraCuu;
    public TraCuuChuyenBayPane() {
        initComponents();
        jpnTraCuu = new JPNTraCuu();
        
        jpnCards.add(jpnTraCuu, "JPNTraCuu");
        cardLayout = (CardLayout)(jpnCards.getLayout());
        cardLayout.show(jpnCards, "JPNTraCuu");
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnCards = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jpnCards.setLayout(new java.awt.CardLayout());
        add(jpnCards, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    
    public void changeLayout(JPanel panel, String type){
        switch(type){
            case "chitiet":
                jpnCards.add(panel, "cardChiTiet");
                cardLayout.show(jpnCards, "cardChiTiet");
                break;
            case "muave":
                jpnCards.add(panel, "cardMuaVe");
                cardLayout.show(jpnCards, "cardMuaVe");
                break;
            case "phieu":
                jpnCards.add(panel, "cardPhieu");
                cardLayout.show(jpnCards, "cardPhieu");
                break;
            case "backChiTiet":
                cardLayout.removeLayoutComponent(panel);
                cardLayout.show(jpnCards, "cardChiTiet");
                break;
            case "back":
                cardLayout.removeLayoutComponent(panel);
                cardLayout.show(jpnCards, "JPNTraCuu");
                break;
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpnCards;
    // End of variables declaration//GEN-END:variables
}
