/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.user.muave;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import pojos.Khachhang;
import pojos.Khachnuocngoai;
import pojos.Khachvietnam;

/**
 *
 * @author DELL
 */
public class DienThongTinKHPanel extends javax.swing.JPanel {

    /**
     * Creates new form DienThongTinKHPanel
     */
    CardLayout cardLayout;
    String typeKH = "none";
    int pos;
    public DienThongTinKHPanel(int pos) {
        initComponents();
        this.pos = pos; 
        jlbSTT.setText(String.valueOf(pos));
        cardLayout = (CardLayout) jpnCards.getLayout();
        
        cardLayout.show(jpnCards, "CardChonLoaiKH");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        jlbSTT = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler45 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jpnCards = new javax.swing.JPanel();
        jpnChonLoaiKhach = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jbtnKHVN = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jbtnKHNuocNgoai = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jpnKhachNuocNgoai = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0));
        jtftennn = new javax.swing.JTextField();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0));
        jtfsdtnn = new javax.swing.JTextField();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0));
        cbbGioiTinh = new javax.swing.JComboBox<>();
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler15 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        filler16 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0));
        ngaySinhnn = new com.toedter.calendar.JDateChooser();
        filler17 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler18 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        filler22 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0));
        jtfQuoctich = new javax.swing.JTextField();
        filler23 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler21 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        filler19 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0));
        jtfHochieu = new javax.swing.JTextField();
        filler20 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jpnKhachVietNam = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        filler24 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0));
        jtftenvn = new javax.swing.JTextField();
        filler25 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler26 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        filler27 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0));
        jtfsdtvn = new javax.swing.JTextField();
        filler28 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler29 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        filler30 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0));
        cbbGioiTinhvn = new javax.swing.JComboBox<>();
        filler32 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler33 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        jPanel13 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        filler34 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0));
        ngaySinhvn = new com.toedter.calendar.JDateChooser();
        filler35 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler36 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        jPanel14 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        filler37 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0));
        jtfcmnd = new javax.swing.JTextField();
        filler38 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler39 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        jPanel15 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        filler40 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0));
        jtfnghe = new javax.swing.JTextField();
        filler41 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler42 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        jPanel16 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        filler43 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0));
        jtfdiachi = new javax.swing.JTextField();
        filler44 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Khách hàng thứ");
        jPanel2.add(jLabel1);
        jPanel2.add(filler1);

        jlbSTT.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlbSTT.setText("1");
        jPanel2.add(jlbSTT);
        jPanel2.add(filler2);
        jPanel2.add(filler45);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jpnCards.setLayout(new java.awt.CardLayout());

        jpnChonLoaiKhach.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));
        jPanel4.add(filler4);

        jbtnKHVN.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jbtnKHVN.setText("Khách Việt Nam");
        jbtnKHVN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKHVNActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnKHVN);
        jPanel4.add(filler5);

        jbtnKHNuocNgoai.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jbtnKHNuocNgoai.setText("Khách nước ngoài");
        jbtnKHNuocNgoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKHNuocNgoaiActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnKHNuocNgoai);
        jPanel4.add(filler3);

        jpnChonLoaiKhach.add(jPanel4, java.awt.BorderLayout.CENTER);

        jpnCards.add(jpnChonLoaiKhach, "cardChonLoaiKH");

        jpnKhachNuocNgoai.setLayout(new javax.swing.BoxLayout(jpnKhachNuocNgoai, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Họ và tên");
        jLabel2.setMaximumSize(new java.awt.Dimension(100, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel3.add(jLabel2);
        jPanel3.add(filler6);

        jtftennn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jtftennn.setMaximumSize(new java.awt.Dimension(250, 30));
        jtftennn.setMinimumSize(new java.awt.Dimension(250, 30));
        jtftennn.setPreferredSize(new java.awt.Dimension(250, 30));
        jPanel3.add(jtftennn);
        jPanel3.add(filler7);

        jpnKhachNuocNgoai.add(jPanel3);
        jpnKhachNuocNgoai.add(filler10);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("SĐT");
        jLabel3.setMaximumSize(new java.awt.Dimension(100, 30));
        jLabel3.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel5.add(jLabel3);
        jPanel5.add(filler8);

        jtfsdtnn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jtfsdtnn.setMaximumSize(new java.awt.Dimension(250, 30));
        jtfsdtnn.setMinimumSize(new java.awt.Dimension(250, 30));
        jtfsdtnn.setPreferredSize(new java.awt.Dimension(250, 30));
        jPanel5.add(jtfsdtnn);
        jPanel5.add(filler9);

        jpnKhachNuocNgoai.add(jPanel5);
        jpnKhachNuocNgoai.add(filler11);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Giới tính");
        jLabel4.setMaximumSize(new java.awt.Dimension(100, 30));
        jLabel4.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel6.add(jLabel4);
        jPanel6.add(filler12);

        cbbGioiTinh.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cbbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cbbGioiTinh.setMaximumSize(new java.awt.Dimension(100, 30));
        cbbGioiTinh.setMinimumSize(new java.awt.Dimension(100, 30));
        cbbGioiTinh.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel6.add(cbbGioiTinh);
        jPanel6.add(filler13);

        jpnKhachNuocNgoai.add(jPanel6);
        jpnKhachNuocNgoai.add(filler15);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Ngày sinh");
        jLabel5.setMaximumSize(new java.awt.Dimension(100, 30));
        jLabel5.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel7.add(jLabel5);
        jPanel7.add(filler16);

        ngaySinhnn.setDateFormatString("dd/MM/yyyy");
        ngaySinhnn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ngaySinhnn.setMaximumSize(new java.awt.Dimension(250, 30));
        ngaySinhnn.setMinimumSize(new java.awt.Dimension(250, 30));
        ngaySinhnn.setPreferredSize(new java.awt.Dimension(250, 30));
        jPanel7.add(ngaySinhnn);
        jPanel7.add(filler17);

        jpnKhachNuocNgoai.add(jPanel7);
        jpnKhachNuocNgoai.add(filler18);

        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.LINE_AXIS));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Quốc tịch");
        jLabel7.setMaximumSize(new java.awt.Dimension(100, 30));
        jLabel7.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabel7.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel9.add(jLabel7);
        jPanel9.add(filler22);

        jtfQuoctich.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jtfQuoctich.setMaximumSize(new java.awt.Dimension(250, 30));
        jtfQuoctich.setMinimumSize(new java.awt.Dimension(250, 30));
        jtfQuoctich.setPreferredSize(new java.awt.Dimension(250, 30));
        jPanel9.add(jtfQuoctich);
        jPanel9.add(filler23);

        jpnKhachNuocNgoai.add(jPanel9);
        jpnKhachNuocNgoai.add(filler21);

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Số hộ chiếu");
        jLabel6.setMaximumSize(new java.awt.Dimension(100, 30));
        jLabel6.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel8.add(jLabel6);
        jPanel8.add(filler19);

        jtfHochieu.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jtfHochieu.setMaximumSize(new java.awt.Dimension(250, 30));
        jtfHochieu.setMinimumSize(new java.awt.Dimension(250, 30));
        jtfHochieu.setPreferredSize(new java.awt.Dimension(250, 30));
        jPanel8.add(jtfHochieu);
        jPanel8.add(filler20);

        jpnKhachNuocNgoai.add(jPanel8);

        jpnCards.add(jpnKhachNuocNgoai, "cardKHNuocNgoai");

        jpnKhachVietNam.setLayout(new javax.swing.BoxLayout(jpnKhachVietNam, javax.swing.BoxLayout.Y_AXIS));

        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Họ và tên");
        jLabel8.setMaximumSize(new java.awt.Dimension(100, 30));
        jLabel8.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabel8.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel10.add(jLabel8);
        jPanel10.add(filler24);

        jtftenvn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jtftenvn.setMaximumSize(new java.awt.Dimension(250, 30));
        jtftenvn.setMinimumSize(new java.awt.Dimension(250, 30));
        jtftenvn.setPreferredSize(new java.awt.Dimension(250, 30));
        jPanel10.add(jtftenvn);
        jPanel10.add(filler25);

        jpnKhachVietNam.add(jPanel10);
        jpnKhachVietNam.add(filler26);

        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.LINE_AXIS));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("SĐT");
        jLabel9.setMaximumSize(new java.awt.Dimension(100, 30));
        jLabel9.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabel9.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel11.add(jLabel9);
        jPanel11.add(filler27);

        jtfsdtvn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jtfsdtvn.setMaximumSize(new java.awt.Dimension(250, 30));
        jtfsdtvn.setMinimumSize(new java.awt.Dimension(250, 30));
        jtfsdtvn.setPreferredSize(new java.awt.Dimension(250, 30));
        jPanel11.add(jtfsdtvn);
        jPanel11.add(filler28);

        jpnKhachVietNam.add(jPanel11);
        jpnKhachVietNam.add(filler29);

        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.LINE_AXIS));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("Giới tính");
        jLabel10.setMaximumSize(new java.awt.Dimension(100, 30));
        jLabel10.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabel10.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel12.add(jLabel10);
        jPanel12.add(filler30);

        cbbGioiTinhvn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cbbGioiTinhvn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cbbGioiTinhvn.setMaximumSize(new java.awt.Dimension(100, 30));
        cbbGioiTinhvn.setMinimumSize(new java.awt.Dimension(100, 30));
        cbbGioiTinhvn.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel12.add(cbbGioiTinhvn);
        jPanel12.add(filler32);

        jpnKhachVietNam.add(jPanel12);
        jpnKhachVietNam.add(filler33);

        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.LINE_AXIS));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Ngày sinh");
        jLabel11.setMaximumSize(new java.awt.Dimension(100, 30));
        jLabel11.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabel11.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel13.add(jLabel11);
        jPanel13.add(filler34);

        ngaySinhvn.setDateFormatString("dd/MM/yyyy");
        ngaySinhvn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ngaySinhvn.setMaximumSize(new java.awt.Dimension(250, 30));
        ngaySinhvn.setMinimumSize(new java.awt.Dimension(250, 30));
        ngaySinhvn.setPreferredSize(new java.awt.Dimension(250, 30));
        jPanel13.add(ngaySinhvn);
        jPanel13.add(filler35);

        jpnKhachVietNam.add(jPanel13);
        jpnKhachVietNam.add(filler36);

        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.LINE_AXIS));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("CMND");
        jLabel12.setMaximumSize(new java.awt.Dimension(100, 30));
        jLabel12.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabel12.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel14.add(jLabel12);
        jPanel14.add(filler37);

        jtfcmnd.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jtfcmnd.setMaximumSize(new java.awt.Dimension(250, 30));
        jtfcmnd.setMinimumSize(new java.awt.Dimension(250, 30));
        jtfcmnd.setPreferredSize(new java.awt.Dimension(250, 30));
        jPanel14.add(jtfcmnd);
        jPanel14.add(filler38);

        jpnKhachVietNam.add(jPanel14);
        jpnKhachVietNam.add(filler39);

        jPanel15.setLayout(new javax.swing.BoxLayout(jPanel15, javax.swing.BoxLayout.LINE_AXIS));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setText("Nghề");
        jLabel13.setMaximumSize(new java.awt.Dimension(100, 30));
        jLabel13.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabel13.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel15.add(jLabel13);
        jPanel15.add(filler40);

        jtfnghe.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jtfnghe.setMaximumSize(new java.awt.Dimension(250, 30));
        jtfnghe.setMinimumSize(new java.awt.Dimension(250, 30));
        jtfnghe.setPreferredSize(new java.awt.Dimension(250, 30));
        jPanel15.add(jtfnghe);
        jPanel15.add(filler41);

        jpnKhachVietNam.add(jPanel15);
        jpnKhachVietNam.add(filler42);

        jPanel16.setLayout(new javax.swing.BoxLayout(jPanel16, javax.swing.BoxLayout.LINE_AXIS));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setText("Địa chỉ");
        jLabel14.setMaximumSize(new java.awt.Dimension(100, 30));
        jLabel14.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabel14.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel16.add(jLabel14);
        jPanel16.add(filler43);

        jtfdiachi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jtfdiachi.setMaximumSize(new java.awt.Dimension(250, 30));
        jtfdiachi.setMinimumSize(new java.awt.Dimension(250, 30));
        jtfdiachi.setPreferredSize(new java.awt.Dimension(250, 30));
        jPanel16.add(jtfdiachi);
        jPanel16.add(filler44);

        jpnKhachVietNam.add(jPanel16);

        jpnCards.add(jpnKhachVietNam, "cardKHVietNam");

        add(jpnCards, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnKHVNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKHVNActionPerformed
        typeKH = "vn";
        cardLayout.show(jpnCards, "cardKHVietNam");
    }//GEN-LAST:event_jbtnKHVNActionPerformed

    private void jbtnKHNuocNgoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKHNuocNgoaiActionPerformed
        typeKH = "foreign";
        cardLayout.show(jpnCards, "cardKHNuocNgoai");
    }//GEN-LAST:event_jbtnKHNuocNgoaiActionPerformed
    
    public Khachvietnam layThongTinKHVN(){
        String ten = jtftenvn.getText();
        String sdt = jtfsdtvn.getText();
        String gioitinh = String.valueOf(cbbGioiTinhvn.getSelectedItem());
        Date ngaysinh;
        try{
            ngaysinh = ngaySinhvn.getCalendar().getTime();
        }catch(NullPointerException ex){
            throw ex;
        }
        String cmnd = jtfcmnd.getText();
        String nghenghiep = jtfnghe.getText();
        String diachi = jtfdiachi.getText();
        
        /*
            String hoTen, String sdt, String gioiTinh, 
            Date ngaySinh, Set phieus, Set hoadonmuaves, String cmnd, String ngheNghiep, String diaChi
        */        
        if(ten.isEmpty() || sdt.isEmpty() || cmnd.isEmpty() || nghenghiep.isEmpty() || diachi.isEmpty())
            throw new NullPointerException();            

        return new Khachvietnam(ten,sdt,gioitinh,ngaysinh,null,null,cmnd,nghenghiep,diachi);
    }
    
    public Khachnuocngoai layThongTinKHNN(){
        String ten = jtftennn.getText();
        String sdt = jtfsdtnn.getText();
        String gioitinh = String.valueOf(cbbGioiTinh.getSelectedItem());
        Date ngaysinh;
        try{
            ngaysinh = ngaySinhnn.getCalendar().getTime();
        }catch(NullPointerException ex){
            throw ex;
        }
        String quoctich = jtfQuoctich.getText();
        String hochieu = jtfHochieu.getText();      
        /*
            String hoTen, String sdt, String gioiTinh, Date ngaySinh, Set phieus, Set hoadonmuaves, 
        String quocTich, String hoChieu) {

        */        
        if(ten.isEmpty() || sdt.isEmpty() || quoctich.isEmpty() || hochieu.isEmpty())
            throw new NullPointerException();            

        return new Khachnuocngoai(ten,sdt,gioitinh,ngaysinh,null,null,quoctich,hochieu);
    }

    public String getTypeKH(){
        return typeKH;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbbGioiTinh;
    private javax.swing.JComboBox<String> cbbGioiTinhvn;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler15;
    private javax.swing.Box.Filler filler16;
    private javax.swing.Box.Filler filler17;
    private javax.swing.Box.Filler filler18;
    private javax.swing.Box.Filler filler19;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler20;
    private javax.swing.Box.Filler filler21;
    private javax.swing.Box.Filler filler22;
    private javax.swing.Box.Filler filler23;
    private javax.swing.Box.Filler filler24;
    private javax.swing.Box.Filler filler25;
    private javax.swing.Box.Filler filler26;
    private javax.swing.Box.Filler filler27;
    private javax.swing.Box.Filler filler28;
    private javax.swing.Box.Filler filler29;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler30;
    private javax.swing.Box.Filler filler32;
    private javax.swing.Box.Filler filler33;
    private javax.swing.Box.Filler filler34;
    private javax.swing.Box.Filler filler35;
    private javax.swing.Box.Filler filler36;
    private javax.swing.Box.Filler filler37;
    private javax.swing.Box.Filler filler38;
    private javax.swing.Box.Filler filler39;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler40;
    private javax.swing.Box.Filler filler41;
    private javax.swing.Box.Filler filler42;
    private javax.swing.Box.Filler filler43;
    private javax.swing.Box.Filler filler44;
    private javax.swing.Box.Filler filler45;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton jbtnKHNuocNgoai;
    private javax.swing.JButton jbtnKHVN;
    private javax.swing.JLabel jlbSTT;
    private javax.swing.JPanel jpnCards;
    private javax.swing.JPanel jpnChonLoaiKhach;
    private javax.swing.JPanel jpnKhachNuocNgoai;
    private javax.swing.JPanel jpnKhachVietNam;
    private javax.swing.JTextField jtfHochieu;
    private javax.swing.JTextField jtfQuoctich;
    private javax.swing.JTextField jtfcmnd;
    private javax.swing.JTextField jtfdiachi;
    private javax.swing.JTextField jtfnghe;
    private javax.swing.JTextField jtfsdtnn;
    private javax.swing.JTextField jtfsdtvn;
    private javax.swing.JTextField jtftennn;
    private javax.swing.JTextField jtftenvn;
    private com.toedter.calendar.JDateChooser ngaySinhnn;
    private com.toedter.calendar.JDateChooser ngaySinhvn;
    // End of variables declaration//GEN-END:variables
}
