/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.user.muave;

import java.awt.Dimension;
import java.util.List;
import ui.user.MainForUser;

/**
 *
 * @author DELL
 */
public class InVePanel extends javax.swing.JPanel {

    /**
     * Creates new form InVePanel
     */
    public InVePanel(List<Integer> mahds) {
        initComponents();
        
        int sl = 10;
        int width = 3*500 + 50;
        int height = (sl/3 + 1)*330 + 50;
        Dimension size = new Dimension(width, height);
        jsp.setMinimumSize(size);
        jsp.setPreferredSize(size);
        
        jpnThongTinVes.setMinimumSize(size);
        jpnThongTinVes.setPreferredSize(size);
        
        
        for(int i = 0; i < mahds.size(); i++){
            jpnThongTinVes.add(new ThongTinVePanel(mahds.get(i)));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jsp = new javax.swing.JScrollPane();
        jpnThongTinVes = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 70), new java.awt.Dimension(0, 70), new java.awt.Dimension(0, 70));
        jButton1 = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 70), new java.awt.Dimension(0, 70), new java.awt.Dimension(0, 70));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(filler2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("In vé chuyến bay");
        jPanel1.add(jLabel1);
        jPanel1.add(filler1);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jsp.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jsp.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jsp.setMaximumSize(new java.awt.Dimension(1600, 32767));
        jsp.setMinimumSize(new java.awt.Dimension(1600, 1500));
        jsp.setPreferredSize(new java.awt.Dimension(1600, 1500));

        jpnThongTinVes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin vé chuyến bay", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jpnThongTinVes.setMaximumSize(new java.awt.Dimension(1600, 32767));
        jpnThongTinVes.setMinimumSize(new java.awt.Dimension(1600, 1500));
        jpnThongTinVes.setPreferredSize(new java.awt.Dimension(1600, 1500));
        jpnThongTinVes.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jsp.setViewportView(jpnThongTinVes);

        add(jsp, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));
        jPanel2.add(filler3);
        jPanel2.add(filler6);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("In vé");
        jButton1.setMaximumSize(new java.awt.Dimension(100, 50));
        jButton1.setMinimumSize(new java.awt.Dimension(100, 50));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jPanel2.add(filler5);
        jPanel2.add(filler4);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int index = MainForUser.getInstance().getCurrentPaneIndex();
        if(index == 0)
            MainForUser.getInstance().getTraCuuPane().changeLayout(this, "ketthuc");
        else if(index == 1)
            MainForUser.getInstance().getXuLyDatVePane().hoanThanhInVe();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jpnThongTinVes;
    private javax.swing.JScrollPane jsp;
    // End of variables declaration//GEN-END:variables
}
