/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.user.muave;

import bus.ChuyenbayBUS;
import bus.HangveBUS;
import bus.HoadonmuaveBUS;
import bus.KhachhangBUS;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import pojos.Chuyenbay;
import pojos.Hoadonmuave;
import pojos.Khachhang;

/**
 *
 * @author DELL
 */
public class ThongTinVePanel extends javax.swing.JPanel {

    /**
     * Creates new form ThongTinVePanel
     */
    public ThongTinVePanel(int mahd) {
        initComponents();
        
        Hoadonmuave hd = HoadonmuaveBUS.getHoaDonByID(mahd);
        
        Chuyenbay cb = ChuyenbayBUS.getChuyenBayByID(hd.getVechuyenbay().getChuyenbay().getMaCb());
        
        jlbMaCB.setText(cb.getMaCb());
        jlbSBDi.setText(cb.getSanbayByMaSbdi().getThanhPho() +" - "+ cb.getSanbayByMaSbdi().getTenSb());
        jlbSBDen.setText(cb.getSanbayByMaSbden().getThanhPho() +" - "+ cb.getSanbayByMaSbden().getTenSb());
        
        DateFormat df = new SimpleDateFormat("hh:mm dd/MM/yyyy");
        
        jlbNgayKhoiHanh.setText(df.format(cb.getNgayKhoiHanh()));
        
        jlbMaSoVe.setText(hd.getVechuyenbay().getMaSoVe());
        jlbTenHangVe.setText(HangveBUS.getTicketLevelName(hd.getVechuyenbay().getHangve().getMaHangVe()));
        jlbGia.setText(String.format("%,.0f VND",hd.getGiaVe()));
        jlbTenKH.setText(hd.getKhachhang().getHoTen());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel14 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jlbMaCB = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jlbSBDi = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jlbSBDen = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jlbNgayKhoiHanh = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jlbMaSoVe = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jlbTenHangVe = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jlbGia = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jlbTenKH = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        setMaximumSize(new java.awt.Dimension(500, 330));
        setMinimumSize(new java.awt.Dimension(500, 330));
        setPreferredSize(new java.awt.Dimension(500, 330));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel14.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel14.setMinimumSize(new java.awt.Dimension(100, 40));
        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.LINE_AXIS));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Mã chuyến bay");
        jPanel14.add(jLabel12);
        jPanel14.add(filler7);

        jlbMaCB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbMaCB.setText("VN-078");
        jPanel14.add(jlbMaCB);

        add(jPanel14);

        jPanel12.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel12.setMinimumSize(new java.awt.Dimension(100, 40));
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.LINE_AXIS));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Sân bay đi");
        jPanel12.add(jLabel11);
        jPanel12.add(filler6);

        jlbSBDi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbSBDi.setText("TPHCM - Sân bay Tân Sơn Nhất");
        jPanel12.add(jlbSBDi);

        add(jPanel12);

        jPanel11.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel11.setMinimumSize(new java.awt.Dimension(100, 40));
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.LINE_AXIS));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Sân bay đến");
        jPanel11.add(jLabel8);
        jPanel11.add(filler5);

        jlbSBDen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbSBDen.setText("Hà Nội - Sân bay Nội Bài");
        jPanel11.add(jlbSBDen);

        add(jPanel11);

        jPanel8.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel8.setMinimumSize(new java.awt.Dimension(100, 40));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Ngày khởi hành ");
        jPanel8.add(jLabel6);
        jPanel8.add(filler1);

        jlbNgayKhoiHanh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbNgayKhoiHanh.setText("07h00 - 18/08/2020");
        jPanel8.add(jlbNgayKhoiHanh);

        add(jPanel8);

        jPanel15.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel15.setMinimumSize(new java.awt.Dimension(100, 40));
        jPanel15.setLayout(new javax.swing.BoxLayout(jPanel15, javax.swing.BoxLayout.LINE_AXIS));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Mã số vé");
        jPanel15.add(jLabel15);
        jPanel15.add(filler10);

        jlbMaSoVe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbMaSoVe.setText("VN-078");
        jPanel15.add(jlbMaSoVe);

        add(jPanel15);

        jPanel10.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel10.setMinimumSize(new java.awt.Dimension(100, 40));
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Hạng vé ");
        jPanel10.add(jLabel10);
        jPanel10.add(filler3);

        jlbTenHangVe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbTenHangVe.setText("Phổ thông");
        jPanel10.add(jlbTenHangVe);

        add(jPanel10);

        jPanel4.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel4.setMinimumSize(new java.awt.Dimension(100, 40));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Thành tiền");
        jPanel4.add(jLabel9);
        jPanel4.add(filler4);

        jlbGia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbGia.setText("500.000 VND");
        jPanel4.add(jlbGia);

        add(jPanel4);

        jPanel5.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel5.setMinimumSize(new java.awt.Dimension(100, 40));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Tên khách hàng");
        jPanel5.add(jLabel13);
        jPanel5.add(filler8);

        jlbTenKH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbTenKH.setText("Trần Văn B");
        jPanel5.add(jlbTenKH);

        add(jPanel5);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel jlbGia;
    private javax.swing.JLabel jlbMaCB;
    private javax.swing.JLabel jlbMaSoVe;
    private javax.swing.JLabel jlbNgayKhoiHanh;
    private javax.swing.JLabel jlbSBDen;
    private javax.swing.JLabel jlbSBDi;
    private javax.swing.JLabel jlbTenHangVe;
    private javax.swing.JLabel jlbTenKH;
    // End of variables declaration//GEN-END:variables
}
