/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.user.muave;

import ui.user.MainForUser;

/**
 *
 * @author DELL
 */
public class XuLyVeDaMuaPanel extends javax.swing.JPanel {

    /**
     * Creates new form XuLyVeDaMuaPanel
     */
    public XuLyVeDaMuaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jlbNgay = new javax.swing.JLabel();
        filler18 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jlbSBDi = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jlbTimeStart = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jlbSBDen = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jlbTimeEnd = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jlbSoDiemDung = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jlbTimeFly = new javax.swing.JLabel();
        filler17 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jpnContainPlaceBreaks = new javax.swing.JPanel();
        jpnPlaceBreaks = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jlbSL = new javax.swing.JLabel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0));
        jLabel9 = new javax.swing.JLabel();
        jlbGia = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel15 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jlbSL1 = new javax.swing.JLabel();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel10 = new javax.swing.JLabel();
        jlbGia1 = new javax.swing.JLabel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel16 = new javax.swing.JLabel();
        jlbGia2 = new javax.swing.JLabel();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel7 = new javax.swing.JPanel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jButton4 = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 5));
        jPanel2.setMaximumSize(new java.awt.Dimension(1000, 50));
        jPanel2.setMinimumSize(new java.awt.Dimension(500, 50));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jlbNgay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbNgay.setText("Chủ nhật Ngày 16 tháng 8 năm 2020");
        jPanel2.add(jlbNgay);
        jPanel2.add(filler18);

        add(jPanel2);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết chuyến bay", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 120));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 120));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 120));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel8.setMaximumSize(new java.awt.Dimension(200, 90));
        jPanel8.setMinimumSize(new java.awt.Dimension(200, 90));
        jPanel8.setPreferredSize(new java.awt.Dimension(200, 90));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setMaximumSize(new java.awt.Dimension(200, 40));
        jPanel3.setMinimumSize(new java.awt.Dimension(200, 40));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jlbSBDi.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlbSBDi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/plane_takeoff.png"))); // NOI18N
        jlbSBDi.setText("Hà nội (HAN)");
        jlbSBDi.setMaximumSize(new java.awt.Dimension(200, 40));
        jlbSBDi.setMinimumSize(new java.awt.Dimension(200, 40));
        jlbSBDi.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(jlbSBDi);

        jPanel8.add(jPanel3);

        jPanel5.setMaximumSize(new java.awt.Dimension(200, 40));
        jPanel5.setMinimumSize(new java.awt.Dimension(200, 40));
        jPanel5.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jlbTimeStart.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlbTimeStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clock.png"))); // NOI18N
        jlbTimeStart.setText("07:00");
        jlbTimeStart.setAlignmentY(0.0F);
        jlbTimeStart.setMaximumSize(new java.awt.Dimension(150, 35));
        jlbTimeStart.setMinimumSize(new java.awt.Dimension(150, 35));
        jlbTimeStart.setPreferredSize(new java.awt.Dimension(150, 35));
        jPanel5.add(jlbTimeStart);

        jPanel8.add(jPanel5);

        jPanel1.add(jPanel8);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/flight.png"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(60, 40));
        jLabel7.setMinimumSize(new java.awt.Dimension(60, 40));
        jLabel7.setPreferredSize(new java.awt.Dimension(60, 40));
        jPanel1.add(jLabel7);

        jPanel12.setMaximumSize(new java.awt.Dimension(250, 90));
        jPanel12.setMinimumSize(new java.awt.Dimension(250, 90));
        jPanel12.setPreferredSize(new java.awt.Dimension(200, 90));
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.Y_AXIS));

        jPanel13.setMaximumSize(new java.awt.Dimension(200, 40));
        jPanel13.setMinimumSize(new java.awt.Dimension(200, 40));
        jPanel13.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jlbSBDen.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlbSBDen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/plane_landing.png"))); // NOI18N
        jlbSBDen.setText("TPHCM (SGN)");
        jlbSBDen.setMaximumSize(new java.awt.Dimension(200, 40));
        jlbSBDen.setMinimumSize(new java.awt.Dimension(200, 40));
        jlbSBDen.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel13.add(jlbSBDen);

        jPanel12.add(jPanel13);

        jPanel14.setMaximumSize(new java.awt.Dimension(200, 40));
        jPanel14.setMinimumSize(new java.awt.Dimension(200, 40));
        jPanel14.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jlbTimeEnd.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlbTimeEnd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clock.png"))); // NOI18N
        jlbTimeEnd.setText("09:00");
        jlbTimeEnd.setAlignmentY(0.0F);
        jlbTimeEnd.setMaximumSize(new java.awt.Dimension(150, 35));
        jlbTimeEnd.setMinimumSize(new java.awt.Dimension(150, 35));
        jlbTimeEnd.setPreferredSize(new java.awt.Dimension(150, 35));
        jPanel14.add(jlbTimeEnd);

        jPanel12.add(jPanel14);

        jPanel1.add(jPanel12);

        jPanel9.setMaximumSize(new java.awt.Dimension(150, 90));
        jPanel9.setMinimumSize(new java.awt.Dimension(150, 90));
        jPanel9.setPreferredSize(new java.awt.Dimension(150, 90));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.Y_AXIS));

        jPanel10.setMaximumSize(new java.awt.Dimension(150, 40));
        jPanel10.setMinimumSize(new java.awt.Dimension(150, 40));
        jPanel10.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jlbSoDiemDung.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlbSoDiemDung.setText("Bay thẳng");
        jlbSoDiemDung.setMaximumSize(new java.awt.Dimension(150, 40));
        jlbSoDiemDung.setMinimumSize(new java.awt.Dimension(150, 40));
        jlbSoDiemDung.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanel10.add(jlbSoDiemDung);

        jPanel9.add(jPanel10);

        jPanel11.setMaximumSize(new java.awt.Dimension(200, 40));
        jPanel11.setMinimumSize(new java.awt.Dimension(200, 40));
        jPanel11.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jlbTimeFly.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlbTimeFly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/timefly.png"))); // NOI18N
        jlbTimeFly.setText("2 giờ");
        jlbTimeFly.setMaximumSize(new java.awt.Dimension(150, 40));
        jlbTimeFly.setMinimumSize(new java.awt.Dimension(150, 40));
        jlbTimeFly.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanel11.add(jlbTimeFly);

        jPanel9.add(jPanel11);

        jPanel1.add(jPanel9);
        jPanel1.add(filler17);

        add(jPanel1);

        jpnContainPlaceBreaks.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Địa điểm dừng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jpnContainPlaceBreaks.setMaximumSize(new java.awt.Dimension(1000, 150));
        jpnContainPlaceBreaks.setMinimumSize(new java.awt.Dimension(12, 100));
        jpnContainPlaceBreaks.setLayout(new javax.swing.BoxLayout(jpnContainPlaceBreaks, javax.swing.BoxLayout.LINE_AXIS));

        jpnPlaceBreaks.setMaximumSize(new java.awt.Dimension(1000, 150));
        jpnPlaceBreaks.setMinimumSize(new java.awt.Dimension(1000, 100));
        jpnPlaceBreaks.setLayout(new javax.swing.BoxLayout(jpnPlaceBreaks, javax.swing.BoxLayout.Y_AXIS));
        jpnContainPlaceBreaks.add(jpnPlaceBreaks);

        add(jpnContainPlaceBreaks);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết vé", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel6.setMaximumSize(new java.awt.Dimension(1000, 100));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Hạng vé: ");
        jPanel6.add(jLabel5);

        jlbSL.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbSL.setText("Phổ thông");
        jPanel6.add(jlbSL);
        jPanel6.add(filler7);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Giá vé: ");
        jPanel6.add(jLabel9);

        jlbGia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbGia.setText("500.000 VND");
        jPanel6.add(jlbGia);
        jPanel6.add(filler4);

        add(jPanel6);

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel15.setMaximumSize(new java.awt.Dimension(1000, 100));
        jPanel15.setLayout(new javax.swing.BoxLayout(jPanel15, javax.swing.BoxLayout.LINE_AXIS));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Họ và tên: ");
        jPanel15.add(jLabel6);

        jlbSL1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbSL1.setText("Trần Văn B");
        jPanel15.add(jlbSL1);
        jPanel15.add(filler8);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("CMND/Hộ chiếu: ");
        jPanel15.add(jLabel10);

        jlbGia1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbGia1.setText("025467333");
        jPanel15.add(jlbGia1);
        jPanel15.add(filler9);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("SDT: ");
        jPanel15.add(jLabel16);

        jlbGia2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbGia2.setText("0123456789");
        jPanel15.add(jlbGia2);
        jPanel15.add(filler10);

        add(jPanel15);

        jPanel7.setMaximumSize(new java.awt.Dimension(1000, 100));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));
        jPanel7.add(filler6);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Hủy vé");
        jButton4.setMaximumSize(new java.awt.Dimension(150, 50));
        jButton4.setMinimumSize(new java.awt.Dimension(150, 50));
        jButton4.setOpaque(false);
        jButton4.setPreferredSize(new java.awt.Dimension(150, 50));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4);
        jPanel7.add(filler5);

        add(jPanel7);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        /*
        if(isConVe)
        MainForUser.getInstance().getTraCuuPane().changeLayout(new MuaVePanel(cb,sl,mahangve), "muave");
        else{
            JLabel label = new JLabel("Hiện tại vé chuyến bay đã được mua/đặt hết. Bạn có thể lập phiếu chờ.");
            label.setFont(new Font("Arial", Font.BOLD, 18));
            label.setForeground(Color.blue);
            JOptionPane.showMessageDialog(null,label,"Warning",JOptionPane.WARNING_MESSAGE);
        }*/
        MainForUser.getInstance().getDoiVePane().hoanThanhHuyVe();
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler17;
    private javax.swing.Box.Filler filler18;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel jlbGia;
    private javax.swing.JLabel jlbGia1;
    private javax.swing.JLabel jlbGia2;
    private javax.swing.JLabel jlbNgay;
    private javax.swing.JLabel jlbSBDen;
    private javax.swing.JLabel jlbSBDi;
    private javax.swing.JLabel jlbSL;
    private javax.swing.JLabel jlbSL1;
    private javax.swing.JLabel jlbSoDiemDung;
    private javax.swing.JLabel jlbTimeEnd;
    private javax.swing.JLabel jlbTimeFly;
    private javax.swing.JLabel jlbTimeStart;
    private javax.swing.JPanel jpnContainPlaceBreaks;
    private javax.swing.JPanel jpnPlaceBreaks;
    // End of variables declaration//GEN-END:variables
}
