package pojos;
// Generated Aug 2, 2020, 12:12:11 AM by Hibernate Tools 4.3.1



/**
 * GiahangvetheocbId generated by hbm2java
 */
public class GiahangvetheocbId  implements java.io.Serializable {


     private String maCb;
     private String maHangVe;

    public GiahangvetheocbId() {
    }

    public GiahangvetheocbId(String maCb, String maHangVe) {
       this.maCb = maCb;
       this.maHangVe = maHangVe;
    }
   
    public String getMaCb() {
        return this.maCb;
    }
    
    public void setMaCb(String maCb) {
        this.maCb = maCb;
    }
    public String getMaHangVe() {
        return this.maHangVe;
    }
    
    public void setMaHangVe(String maHangVe) {
        this.maHangVe = maHangVe;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GiahangvetheocbId) ) return false;
		 GiahangvetheocbId castOther = ( GiahangvetheocbId ) other; 
         
		 return ( (this.getMaCb()==castOther.getMaCb()) || ( this.getMaCb()!=null && castOther.getMaCb()!=null && this.getMaCb().equals(castOther.getMaCb()) ) )
 && ( (this.getMaHangVe()==castOther.getMaHangVe()) || ( this.getMaHangVe()!=null && castOther.getMaHangVe()!=null && this.getMaHangVe().equals(castOther.getMaHangVe()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMaCb() == null ? 0 : this.getMaCb().hashCode() );
         result = 37 * result + ( getMaHangVe() == null ? 0 : this.getMaHangVe().hashCode() );
         return result;
   }   


}


