package pojos;
// Generated Aug 2, 2020, 11:17:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Hangve generated by hbm2java
 */
public class Hangve  implements java.io.Serializable {


     private String maHangVe;
     private String tenHangVe;
     private Set vechuyenbays = new HashSet(0);
     private Set giahangvetheocbs = new HashSet(0);

    public Hangve() {
    }

	
    public Hangve(String maHangVe) {
        this.maHangVe = maHangVe;
    }
    public Hangve(String maHangVe, String tenHangVe, Set vechuyenbays, Set giahangvetheocbs) {
       this.maHangVe = maHangVe;
       this.tenHangVe = tenHangVe;
       this.vechuyenbays = vechuyenbays;
       this.giahangvetheocbs = giahangvetheocbs;
    }
   
    public String getMaHangVe() {
        return this.maHangVe;
    }
    
    public void setMaHangVe(String maHangVe) {
        this.maHangVe = maHangVe;
    }
    public String getTenHangVe() {
        return this.tenHangVe;
    }
    
    public void setTenHangVe(String tenHangVe) {
        this.tenHangVe = tenHangVe;
    }
    public Set getVechuyenbays() {
        return this.vechuyenbays;
    }
    
    public void setVechuyenbays(Set vechuyenbays) {
        this.vechuyenbays = vechuyenbays;
    }
    public Set getGiahangvetheocbs() {
        return this.giahangvetheocbs;
    }
    
    public void setGiahangvetheocbs(Set giahangvetheocbs) {
        this.giahangvetheocbs = giahangvetheocbs;
    }




}


