package pojos;
// Generated Aug 2, 2020, 11:17:00 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.Set;



/**
 * Khachnuocngoai generated by hbm2java
 */
public class Khachnuocngoai extends Khachhang implements java.io.Serializable {

     private String quocTich;
     private String hoChieu;

    public Khachnuocngoai() {
    }

    public Khachnuocngoai(String hoTen, String sdt, String gioiTinh, Date ngaySinh, Set phieus, Set hoadonmuaves, String quocTich, String hoChieu) {
       super(hoTen, sdt, gioiTinh, ngaySinh, phieus, hoadonmuaves);
       this.quocTich = quocTich;
       this.hoChieu = hoChieu;
    }

    public String getQuocTich() {
        return this.quocTich;
    }
    
    public void setQuocTich(String quocTich) {
        this.quocTich = quocTich;
    }
    public String getHoChieu() {
        return this.hoChieu;
    }
    
    public void setHoChieu(String hoChieu) {
        this.hoChieu = hoChieu;
    }

    @Override
    public String toString() {
        String str = ""
                + "Khach Nuoc Ngoai\n"
                + "-Ho ten: " + this.hoTen + "\n"
                + "-sdt: " + this.sdt + "\n"
                + "-gioiTinh: " + this.gioiTinh + "\n"
                + "-ngaySinh: " + this.ngaySinh + "\n"
                + "-quocTich: " + this.quocTich + "\n"
                + "-hoChieu: " + this.hoChieu + "\n";
        return str;
    }


}


