package pojos;
// Generated Aug 2, 2020, 12:12:11 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Khachhang generated by hbm2java
 */
public class Khachhang  implements java.io.Serializable {


     private int maKh;
     private String hoTen;
     private String sdt;
     private String gioiTinh;
     private Date ngaySinh;
     private Khachvietnam khachvietnam;
     private Khachnuocngoai khachnuocngoai;
     private Set phieus = new HashSet(0);
     private Set hoadonmuaves = new HashSet(0);

    public Khachhang() {
    }

	
    public Khachhang(int maKh) {
        this.maKh = maKh;
    }
    public Khachhang(int maKh, String hoTen, String sdt, String gioiTinh, Date ngaySinh, Khachvietnam khachvietnam, Khachnuocngoai khachnuocngoai, Set phieus, Set hoadonmuaves) {
       this.maKh = maKh;
       this.hoTen = hoTen;
       this.sdt = sdt;
       this.gioiTinh = gioiTinh;
       this.ngaySinh = ngaySinh;
       this.khachvietnam = khachvietnam;
       this.khachnuocngoai = khachnuocngoai;
       this.phieus = phieus;
       this.hoadonmuaves = hoadonmuaves;
    }
   
    public int getMaKh() {
        return this.maKh;
    }
    
    public void setMaKh(int maKh) {
        this.maKh = maKh;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getSdt() {
        return this.sdt;
    }
    
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }
    public String getGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(String gioiTinh) {
        this.gioiTinh = gioiTinh;
    }
    public Date getNgaySinh() {
        return this.ngaySinh;
    }
    
    public void setNgaySinh(Date ngaySinh) {
        this.ngaySinh = ngaySinh;
    }
    public Khachvietnam getKhachvietnam() {
        return this.khachvietnam;
    }
    
    public void setKhachvietnam(Khachvietnam khachvietnam) {
        this.khachvietnam = khachvietnam;
    }
    public Khachnuocngoai getKhachnuocngoai() {
        return this.khachnuocngoai;
    }
    
    public void setKhachnuocngoai(Khachnuocngoai khachnuocngoai) {
        this.khachnuocngoai = khachnuocngoai;
    }
    public Set getPhieus() {
        return this.phieus;
    }
    
    public void setPhieus(Set phieus) {
        this.phieus = phieus;
    }
    public Set getHoadonmuaves() {
        return this.hoadonmuaves;
    }
    
    public void setHoadonmuaves(Set hoadonmuaves) {
        this.hoadonmuaves = hoadonmuaves;
    }




}


