package pojos;
// Generated Aug 2, 2020, 11:17:00 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.Set;



/**
 * Khachvietnam generated by hbm2java
 */
public class Khachvietnam extends Khachhang implements java.io.Serializable {

     private String cmnd;
     private String ngheNghiep;
     private String diaChi;

    public Khachvietnam() {
    }

    public Khachvietnam(String hoTen, String sdt, String gioiTinh, Date ngaySinh, Set phieus, Set hoadonmuaves, String cmnd, String ngheNghiep, String diaChi) {
        super(hoTen, sdt, gioiTinh, ngaySinh, phieus, hoadonmuaves);
       this.cmnd = cmnd;
       this.ngheNghiep = ngheNghiep;
       this.diaChi = diaChi;
    }

    public String getCmnd() {
        return this.cmnd;
    }
    
    public void setCmnd(String cmnd) {
        this.cmnd = cmnd;
    }
    public String getNgheNghiep() {
        return this.ngheNghiep;
    }
    
    public void setNgheNghiep(String ngheNghiep) {
        this.ngheNghiep = ngheNghiep;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }

    @Override
    public String toString() {
        String str = ""
                + "Khach Viet Nam\n"
                + "-Ho ten: " + this.hoTen + "\n"
                + "-sdt: " + this.sdt + "\n"
                + "-gioiTinh: " + this.gioiTinh + "\n"
                + "-ngaySinh: " + this.ngaySinh + "\n"
                + "-cmnd: " + this.cmnd + "\n"
                + "-diaChi: " + this.diaChi + "\n"
                + "-ngheNghiep: " + this.ngheNghiep + "\n";

        return str;
    }


}


