package pojos;
// Generated Aug 2, 2020, 12:12:11 AM by Hibernate Tools 4.3.1



/**
 * Khachnuocngoai generated by hbm2java
 */
public class Khachnuocngoai  implements java.io.Serializable {


     private int maKh;
     private Khachhang khachhang;
     private String quocTich;
     private String hoChieu;

    public Khachnuocngoai() {
    }

	
    public Khachnuocngoai(Khachhang khachhang) {
        this.khachhang = khachhang;
    }
    public Khachnuocngoai(Khachhang khachhang, String quocTich, String hoChieu) {
       this.khachhang = khachhang;
       this.quocTich = quocTich;
       this.hoChieu = hoChieu;
    }
   
    public int getMaKh() {
        return this.maKh;
    }
    
    public void setMaKh(int maKh) {
        this.maKh = maKh;
    }
    public Khachhang getKhachhang() {
        return this.khachhang;
    }
    
    public void setKhachhang(Khachhang khachhang) {
        this.khachhang = khachhang;
    }
    public String getQuocTich() {
        return this.quocTich;
    }
    
    public void setQuocTich(String quocTich) {
        this.quocTich = quocTich;
    }
    public String getHoChieu() {
        return this.hoChieu;
    }
    
    public void setHoChieu(String hoChieu) {
        this.hoChieu = hoChieu;
    }




}


