package pojos;
// Generated Aug 2, 2020, 12:12:11 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Lichsugiahangvecb generated by hbm2java
 */
public class Lichsugiahangvecb  implements java.io.Serializable {


     private Integer idCapNhat;
     private Giahangvetheocb giahangvetheocb;
     private Date ngayCapNhat;
     private BigDecimal giaCapNhat;

    public Lichsugiahangvecb() {
    }

    public Lichsugiahangvecb(Giahangvetheocb giahangvetheocb, Date ngayCapNhat, BigDecimal giaCapNhat) {
       this.giahangvetheocb = giahangvetheocb;
       this.ngayCapNhat = ngayCapNhat;
       this.giaCapNhat = giaCapNhat;
    }
   
    public Integer getIdCapNhat() {
        return this.idCapNhat;
    }
    
    public void setIdCapNhat(Integer idCapNhat) {
        this.idCapNhat = idCapNhat;
    }
    public Giahangvetheocb getGiahangvetheocb() {
        return this.giahangvetheocb;
    }
    
    public void setGiahangvetheocb(Giahangvetheocb giahangvetheocb) {
        this.giahangvetheocb = giahangvetheocb;
    }
    public Date getNgayCapNhat() {
        return this.ngayCapNhat;
    }
    
    public void setNgayCapNhat(Date ngayCapNhat) {
        this.ngayCapNhat = ngayCapNhat;
    }
    public BigDecimal getGiaCapNhat() {
        return this.giaCapNhat;
    }
    
    public void setGiaCapNhat(BigDecimal giaCapNhat) {
        this.giaCapNhat = giaCapNhat;
    }




}


