package pojos;
// Generated Aug 2, 2020, 11:17:00 PM by Hibernate Tools 4.3.1

import java.util.Date;




/**
 * Phieucho generated by hbm2java
 */
public class Phieucho extends Phieu implements java.io.Serializable {

    private Chuyenbay chuyenbay;

    public Phieucho() {
    }
    
    public Phieucho(Date ngayDat, Chuyenbay chuyenbay) {
        super(ngayDat);
        this.chuyenbay = chuyenbay;
    }

    public Phieucho(Khachhang khachhang, Date ngayDat, String tinhTrang, Chuyenbay chuyenbay) {
        super(khachhang, ngayDat, tinhTrang);
        this.chuyenbay = chuyenbay;
    }

    public Chuyenbay getChuyenbay() {
        return this.chuyenbay;
    }
    
    public void setChuyenbay(Chuyenbay chuyenbay) {
        this.chuyenbay = chuyenbay;
    }





}


