package pojos;
// Generated Aug 2, 2020, 11:17:00 PM by Hibernate Tools 4.3.1



/**
 * Phieudatcho generated by hbm2java
 */
public class Phieudatcho  implements java.io.Serializable {


     private int idPhieu;
     private Phieu phieu;
     private Vechuyenbay vechuyenbay;

    public Phieudatcho() {
    }

    public Phieudatcho(Phieu phieu, Vechuyenbay vechuyenbay) {
       this.phieu = phieu;
       this.vechuyenbay = vechuyenbay;
    }
   
    public int getIdPhieu() {
        return this.idPhieu;
    }
    
    public void setIdPhieu(int idPhieu) {
        this.idPhieu = idPhieu;
    }
    public Phieu getPhieu() {
        return this.phieu;
    }
    
    public void setPhieu(Phieu phieu) {
        this.phieu = phieu;
    }
    public Vechuyenbay getVechuyenbay() {
        return this.vechuyenbay;
    }
    
    public void setVechuyenbay(Vechuyenbay vechuyenbay) {
        this.vechuyenbay = vechuyenbay;
    }




}


