package pojos;
// Generated Aug 2, 2020, 11:17:00 PM by Hibernate Tools 4.3.1



/**
 * Phieudatcho generated by hbm2java
 */
public class Phieudatcho extends Phieu implements java.io.Serializable {

    private Vechuyenbay vechuyenbay;

    public Phieudatcho() {
    }

    public Phieudatcho(Vechuyenbay vechuyenbay) {
       this.vechuyenbay = vechuyenbay;
    }
   
    public Vechuyenbay getVechuyenbay() {
        return this.vechuyenbay;
    }
    
    public void setVechuyenbay(Vechuyenbay vechuyenbay) {
        this.vechuyenbay = vechuyenbay;
    }




}


