package pojos;
// Generated Aug 2, 2020, 12:12:11 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Phieu generated by hbm2java
 */
public class Phieu  implements java.io.Serializable {


     private Integer idPhieu;
     private Khachhang khachhang;
     private Date ngayDat;
     private String tinhTrang;
     private Phieudatcho phieudatcho;
     private Phieucho phieucho;

    public Phieu() {
    }

	
    public Phieu(Date ngayDat) {
        this.ngayDat = ngayDat;
    }
    public Phieu(Khachhang khachhang, Date ngayDat, String tinhTrang, Phieudatcho phieudatcho, Phieucho phieucho) {
       this.khachhang = khachhang;
       this.ngayDat = ngayDat;
       this.tinhTrang = tinhTrang;
       this.phieudatcho = phieudatcho;
       this.phieucho = phieucho;
    }
   
    public Integer getIdPhieu() {
        return this.idPhieu;
    }
    
    public void setIdPhieu(Integer idPhieu) {
        this.idPhieu = idPhieu;
    }
    public Khachhang getKhachhang() {
        return this.khachhang;
    }
    
    public void setKhachhang(Khachhang khachhang) {
        this.khachhang = khachhang;
    }
    public Date getNgayDat() {
        return this.ngayDat;
    }
    
    public void setNgayDat(Date ngayDat) {
        this.ngayDat = ngayDat;
    }
    public String getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(String tinhTrang) {
        this.tinhTrang = tinhTrang;
    }
    public Phieudatcho getPhieudatcho() {
        return this.phieudatcho;
    }
    
    public void setPhieudatcho(Phieudatcho phieudatcho) {
        this.phieudatcho = phieudatcho;
    }
    public Phieucho getPhieucho() {
        return this.phieucho;
    }
    
    public void setPhieucho(Phieucho phieucho) {
        this.phieucho = phieucho;
    }




}


