package pojos;
// Generated Aug 2, 2020, 11:17:00 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Phieu generated by hbm2java
 */
public class Phieu  implements java.io.Serializable {


    protected Integer idPhieu;
    protected Khachhang khachhang;
    protected Date ngayDat;
    protected String tinhTrang;

    public Phieu() {
    }

	
    public Phieu(Date ngayDat) {
        this.ngayDat = ngayDat;
    }
    public Phieu(Khachhang khachhang, Date ngayDat, String tinhTrang) {
       this.khachhang = khachhang;
       this.ngayDat = ngayDat;
        this.tinhTrang = tinhTrang;
    }
   
    public Integer getIdPhieu() {
        return this.idPhieu;
    }
    
    public void setIdPhieu(Integer idPhieu) {
        this.idPhieu = idPhieu;
    }
    public Khachhang getKhachhang() {
        return this.khachhang;
    }
    
    public void setKhachhang(Khachhang khachhang) {
        this.khachhang = khachhang;
    }
    public Date getNgayDat() {
        return this.ngayDat;
    }
    
    public void setNgayDat(Date ngayDat) {
        this.ngayDat = ngayDat;
    }
    public String getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(String tinhTrang) {
        this.tinhTrang = tinhTrang;
    }





}


