package pojos;
// Generated Aug 2, 2020, 11:17:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sanbay generated by hbm2java
 */
public class Sanbay  implements java.io.Serializable {


     private Integer maSb;
     private String tenSb;
     private String thanhPho;
     private String quocGia;
     private Set chuyenbaysForMaSbden = new HashSet(0);
     private Set chuyenbaysForMaSbdi = new HashSet(0);
     private Set sanbaytrunggians = new HashSet(0);

    public Sanbay() {
    }

    public Sanbay(String tenSb, String thanhPho, String quocGia, Set chuyenbaysForMaSbden, Set chuyenbaysForMaSbdi, Set sanbaytrunggians) {
       this.tenSb = tenSb;
       this.thanhPho = thanhPho;
       this.quocGia = quocGia;
       this.chuyenbaysForMaSbden = chuyenbaysForMaSbden;
       this.chuyenbaysForMaSbdi = chuyenbaysForMaSbdi;
       this.sanbaytrunggians = sanbaytrunggians;
    }
   
    public Integer getMaSb() {
        return this.maSb;
    }
    
    public void setMaSb(Integer maSb) {
        this.maSb = maSb;
    }
    public String getTenSb() {
        return this.tenSb;
    }
    
    public void setTenSb(String tenSb) {
        this.tenSb = tenSb;
    }
    
    public String getThanhPho() {
        return this.thanhPho;
    }
    
    public void setThanhPho(String thanhPho) {
        this.thanhPho = thanhPho;
    }
    
    public String getQuocGia() {
        return this.quocGia;
    }
    
    public Set getChuyenbaysForMaSbden() {
        return this.chuyenbaysForMaSbden;
    }
    
    public void setChuyenbaysForMaSbden(Set chuyenbaysForMaSbden) {
        this.chuyenbaysForMaSbden = chuyenbaysForMaSbden;
    }
    public Set getChuyenbaysForMaSbdi() {
        return this.chuyenbaysForMaSbdi;
    }
    
    public void setChuyenbaysForMaSbdi(Set chuyenbaysForMaSbdi) {
        this.chuyenbaysForMaSbdi = chuyenbaysForMaSbdi;
    }
    public Set getSanbaytrunggians() {
        return this.sanbaytrunggians;
    }
    
    public void setSanbaytrunggians(Set sanbaytrunggians) {
        this.sanbaytrunggians = sanbaytrunggians;
    }




}


