package pojos;
// Generated Aug 2, 2020, 10:12:15 PM by Hibernate Tools 4.3.1



/**
 * Taikhoan generated by hbm2java
 */
public class Taikhoan  implements java.io.Serializable {


     private int idNhanVien;
     private Nhanvien nhanvien;
     private String tenTaiKhoan;
     private String matKhau;

    public Taikhoan() {
    }

    public Taikhoan(Nhanvien nhanvien, String tenTaiKhoan, String matKhau) {
       this.nhanvien = nhanvien;
       this.tenTaiKhoan = tenTaiKhoan;
       this.matKhau = matKhau;
    }
   
    public int getIdNhanVien() {
        return this.idNhanVien;
    }
    
    public void setIdNhanVien(int idNhanVien) {
        this.idNhanVien = idNhanVien;
    }
    public Nhanvien getNhanvien() {
        return this.nhanvien;
    }
    
    public void setNhanvien(Nhanvien nhanvien) {
        this.nhanvien = nhanvien;
    }
    public String getTenTaiKhoan() {
        return this.tenTaiKhoan;
    }
    
    public void setTenTaiKhoan(String tenTaiKhoan) {
        this.tenTaiKhoan = tenTaiKhoan;
    }
    public String getMatKhau() {
        return this.matKhau;
    }
    
    public void setMatKhau(String matKhau) {
        this.matKhau = matKhau;
    }




}


