/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.user.phieu;

import bus.ChuyenbayBUS;
import bus.PhieuchoBUS;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Iterator;
import java.util.List;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import pojos.Chuyenbay;
import pojos.Phieucho;

/**
 *
 * @author DELL
 */
public class QuanLyPhieuChoPanel extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyPhieuChoPanel
     */
    CardLayout cardLayout;
    int indexselected = -1;
    List<Chuyenbay> listCB;
    public QuanLyPhieuChoPanel() {
        initComponents();
        cardLayout = (CardLayout)jpnContainCards.getLayout();
        cardLayout.show(jpnContainCards, "cardDSQL");
        btnChonCB.setEnabled(false);
        listCB = ChuyenbayBUS.getTatCaChuyenBay();//lấy tất cả các chuyến bay chưa khởi hành
        DefaultTableModel model = new DefaultTableModel(
                new String[]{"Mã CB", "Sân bay đi", "Sân bay đến","Thời gian khởi hành", "Số lượng phiếu chờ cần thông báo"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        for(int i = 0; i< listCB.size(); i++){
            Chuyenbay cb = listCB.get(i);
            String sbdi = cb.getSanbayByMaSbdi().getThanhPho() +" - "+cb.getSanbayByMaSbdi().getTenSb();
            String sbden = cb.getSanbayByMaSbden().getThanhPho() +" - "+cb.getSanbayByMaSbden().getTenSb();
            DateFormat df = new SimpleDateFormat("hh:mm dd/MM/yyyy");
            model.addRow(new Object[]{cb.getMaCb(),sbdi, sbden, 
                df.format(cb.getNgayKhoiHanh()),cb.getPhieuchos().size()});
        }
        
        jtbDSCB.setModel(model);
        jtbDSCB.setFont(new java.awt.Font("Tahoma", 0, 16));
        jtbDSCB.getTableHeader().setReorderingAllowed(false);
        jtbDSCB.getTableHeader().setFont(new java.awt.Font("Tahoma", 1, 16));
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( SwingConstants.CENTER );
        for(int i = 0; i < 5; i++)
            jtbDSCB.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnContainCards = new javax.swing.JPanel();
        jpndsql = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbDSCB = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btnChonCB = new javax.swing.JButton();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 70), new java.awt.Dimension(0, 70), new java.awt.Dimension(0, 70));
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setLayout(new java.awt.BorderLayout());

        jpnContainCards.setLayout(new java.awt.CardLayout());

        jpndsql.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 10, 1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("QUẢN LÝ PHIẾU CHỜ CỦA CÁC CHUYẾN BAY");
        jPanel1.add(jLabel3);

        jpndsql.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jtbDSCB.setAutoCreateRowSorter(true);
        jtbDSCB.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jtbDSCB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtbDSCB.setRowHeight(35);
        jtbDSCB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbDSCBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbDSCB);

        jpndsql.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));
        jPanel3.add(filler7);

        btnChonCB.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnChonCB.setText("Chọn chuyến bay");
        btnChonCB.setMaximumSize(new java.awt.Dimension(200, 50));
        btnChonCB.setMinimumSize(new java.awt.Dimension(200, 50));
        btnChonCB.setPreferredSize(new java.awt.Dimension(200, 50));
        btnChonCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonCBActionPerformed(evt);
            }
        });
        jPanel3.add(btnChonCB);
        jPanel3.add(filler11);
        jPanel3.add(filler8);

        jpndsql.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jpnContainCards.add(jpndsql, "cardDSQL");

        add(jpnContainCards, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jtbDSCBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbDSCBMouseClicked
        btnChonCB.setEnabled(true);
    }//GEN-LAST:event_jtbDSCBMouseClicked

    private void btnChonCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonCBActionPerformed
        indexselected = jtbDSCB.getSelectedRow();
        jpnContainCards.add(new ThongBaoPhieuChoPanel(listCB.get(indexselected)), "cardThongBao");
        cardLayout.show(jpnContainCards, "cardThongBao");
    }//GEN-LAST:event_btnChonCBActionPerformed

    public void hoanThanhThongBao(ThongBaoPhieuChoPanel panel, String type){
        cardLayout.removeLayoutComponent(panel);
        if(type.equals("remove")){
            //xóa trong database
            Iterator<Phieucho> phieucs = listCB.get(indexselected).getPhieuchos().iterator();
            while(phieucs.hasNext()){
                PhieuchoBUS.delete(phieucs.next());
            }
            //xóa hàng đó trong jtable
            DefaultTableModel model = (DefaultTableModel)jtbDSCB.getModel();
            model.removeRow(indexselected);
            jtbDSCB.setModel(model);
            btnChonCB.setVisible(false);
            indexselected = -1;
        }
        cardLayout.show(jpnContainCards, "cardDSQL");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonCB;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpnContainCards;
    private javax.swing.JPanel jpndsql;
    private javax.swing.JTable jtbDSCB;
    // End of variables declaration//GEN-END:variables
}
